import { CareerQuestion } from '@/types/career-matching';

export const careerQuestionnaire: CareerQuestion[] = [
  {
    id: 'interests-1',
    question: 'What areas are you most interested in?',
    type: 'multiple-choice',
    category: 'interests',
    options: [
      { value: 'technology', label: 'Technology & Programming' },
      { value: 'design', label: 'Design & Creativity' },
      { value: 'health', label: 'Healthcare & Wellness' },
      { value: 'finance', label: 'Finance & Business' },
      { value: 'marketing', label: 'Marketing & Communication' },
      { value: 'data', label: 'Data & Analytics' },
      { value: 'people', label: 'Working with People' },
      { value: 'coaching', label: 'Teaching & Coaching' },
    ],
    required: true,
    helpText: 'Select all that apply',
  },
  {
    id: 'interests-2',
    question: 'Which daily activities sound most appealing?',
    type: 'multiple-choice',
    category: 'interests',
    options: [
      { value: 'coding', label: 'Writing code and building software' },
      { value: 'design', label: 'Creating visual designs or user experiences' },
      { value: 'analysis', label: 'Analyzing data and finding insights' },
      { value: 'communication', label: 'Communicating with clients or teams' },
      { value: 'strategy', label: 'Developing strategies and plans' },
      { value: 'problem-solving', label: 'Solving complex problems' },
      { value: 'helping', label: 'Helping others achieve their goals' },
      { value: 'creating-content', label: 'Creating content (writing, media, etc.)' },
    ],
    required: true,
    helpText: 'Choose 3-5 activities',
  },
  {
    id: 'skills-1',
    question: 'What technical or professional skills do you have?',
    type: 'multiple-choice',
    category: 'skills',
    options: [
      { value: 'programming', label: 'Programming/Software Development' },
      { value: 'design-tools', label: 'Design Tools (Figma, Adobe, etc.)' },
      { value: 'data-analysis', label: 'Data Analysis' },
      { value: 'marketing-tools', label: 'Marketing Tools' },
      { value: 'financial-analysis', label: 'Financial Analysis' },
      { value: 'project-management', label: 'Project Management' },
      { value: 'communication', label: 'Written/Verbal Communication' },
      { value: 'coaching', label: 'Coaching/Training' },
      { value: 'sales', label: 'Sales/Business Development' },
    ],
    required: true,
    helpText: 'Select all that apply',
  },
  {
    id: 'skills-2',
    question: 'Rate your comfort with learning new technologies',
    type: 'rating',
    category: 'skills',
    min: 1,
    max: 5,
    required: true,
    helpText: '1 = Prefer familiar tools, 5 = Love learning new tech',
  },
  {
    id: 'experience-1',
    question: 'What is your current experience level?',
    type: 'single-choice',
    category: 'experience',
    options: [
      { value: 'entry', label: 'Entry Level (0-2 years)' },
      { value: 'mid', label: 'Mid Level (3-5 years)' },
      { value: 'senior', label: 'Senior Level (6-10 years)' },
      { value: 'executive', label: 'Executive (10+ years)' },
    ],
    required: true,
  },
  {
    id: 'experience-2',
    question: 'How many years of professional experience do you have?',
    type: 'range',
    category: 'experience',
    min: 0,
    max: 30,
    required: true,
  },
  {
    id: 'experience-3',
    question: 'What industries have you worked in?',
    type: 'multiple-choice',
    category: 'experience',
    options: [
      { value: 'tech', label: 'Technology' },
      { value: 'healthcare', label: 'Healthcare' },
      { value: 'finance', label: 'Finance' },
      { value: 'retail', label: 'Retail' },
      { value: 'education', label: 'Education' },
      { value: 'marketing', label: 'Marketing/Advertising' },
      { value: 'consulting', label: 'Consulting' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
    helpText: 'Select all that apply',
  },
  {
    id: 'personality-1',
    question: 'How do you prefer to work?',
    type: 'single-choice',
    category: 'personality',
    options: [
      { value: 'independent', label: 'Independently - I work best alone' },
      { value: 'collaborative', label: 'Collaboratively - I thrive in team settings' },
      { value: 'mixed', label: 'Mixed - I enjoy both solo and team work' },
    ],
    required: true,
  },
  {
    id: 'personality-2',
    question: 'What work pace do you prefer?',
    type: 'single-choice',
    category: 'personality',
    options: [
      { value: 'fast-paced', label: 'Fast-paced with constant change' },
      { value: 'steady', label: 'Steady and predictable' },
      { value: 'varied', label: 'Varied - some fast, some steady' },
    ],
    required: true,
  },
  {
    id: 'personality-3',
    question: 'How do you approach problem-solving?',
    type: 'single-choice',
    category: 'personality',
    options: [
      { value: 'analytical', label: 'Analytical - Data-driven, logical approach' },
      { value: 'creative', label: 'Creative - Innovative, outside-the-box thinking' },
      { value: 'practical', label: 'Practical - Tried-and-true methods' },
      { value: 'mixed', label: 'Mixed - Depends on the situation' },
    ],
    required: true,
  },
  {
    id: 'personality-4',
    question: 'How much communication do you prefer in your role?',
    type: 'single-choice',
    category: 'personality',
    options: [
      { value: 'frequent', label: 'Frequent - Constant meetings and interaction' },
      { value: 'moderate', label: 'Moderate - Regular check-ins and updates' },
      { value: 'minimal', label: 'Minimal - Mostly independent work' },
    ],
    required: true,
  },
  {
    id: 'personality-5',
    question: 'Are you interested in leadership or management roles?',
    type: 'single-choice',
    category: 'personality',
    options: [
      { value: 'yes', label: 'Yes, I want to lead teams' },
      { value: 'no', label: 'No, I prefer individual contributor roles' },
      { value: 'maybe', label: 'Maybe, open to it in the future' },
    ],
    required: true,
  },
  {
    id: 'preferences-1',
    question: 'What work environment do you prefer?',
    type: 'multiple-choice',
    category: 'preferences',
    options: [
      { value: 'remote', label: 'Remote (work from home)' },
      { value: 'hybrid', label: 'Hybrid (mix of remote and office)' },
      { value: 'onsite', label: 'On-site (in-person at office)' },
    ],
    required: true,
    helpText: 'Select all you would consider',
  },
  {
    id: 'preferences-2',
    question: 'What is your minimum desired salary?',
    type: 'range',
    category: 'preferences',
    min: 30000,
    max: 200000,
    required: true,
    helpText: 'Annual salary in USD',
  },
  {
    id: 'preferences-3',
    question: 'What is your maximum desired salary?',
    type: 'range',
    category: 'preferences',
    min: 50000,
    max: 300000,
    required: true,
    helpText: 'Annual salary in USD',
  },
  {
    id: 'preferences-4',
    question: 'How important is work-life balance to you?',
    type: 'single-choice',
    category: 'preferences',
    options: [
      { value: 'high', label: 'Very Important - I prioritize personal time' },
      { value: 'medium', label: 'Somewhat Important - I can be flexible' },
      { value: 'low', label: 'Less Important - I\'m willing to work long hours' },
    ],
    required: true,
  },
  {
    id: 'preferences-5',
    question: 'Are you willing to travel for work?',
    type: 'single-choice',
    category: 'preferences',
    options: [
      { value: 'yes', label: 'Yes, I enjoy traveling' },
      { value: 'no', label: 'No, I prefer to stay local' },
      { value: 'sometimes', label: 'Occasionally is fine' },
    ],
    required: true,
  },
  {
    id: 'preferences-6',
    question: 'Which career categories interest you most?',
    type: 'multiple-choice',
    category: 'preferences',
    options: [
      { value: 'tech', label: 'Technology' },
      { value: 'healthcare', label: 'Healthcare' },
      { value: 'finance', label: 'Finance' },
      { value: 'marketing', label: 'Marketing' },
      { value: 'design', label: 'Design' },
      { value: 'wellness', label: 'Wellness & Fitness' },
    ],
    required: false,
    helpText: 'Leave blank to see all categories',
  },
  {
    id: 'education-1',
    question: 'What is your highest level of education?',
    type: 'single-choice',
    category: 'education',
    options: [
      { value: 'high-school', label: 'High School Diploma' },
      { value: 'associates', label: 'Associate Degree' },
      { value: 'bachelors', label: 'Bachelor\'s Degree' },
      { value: 'masters', label: 'Master\'s Degree' },
      { value: 'phd', label: 'PhD or Doctorate' },
    ],
    required: true,
  },
  {
    id: 'education-2',
    question: 'What was/is your field of study?',
    type: 'text',
    category: 'education',
    required: false,
    helpText: 'e.g., Computer Science, Business, Psychology',
  },
  {
    id: 'education-3',
    question: 'Are you willing to get additional certifications?',
    type: 'single-choice',
    category: 'education',
    options: [
      { value: 'yes', label: 'Yes, I\'m open to certifications' },
      { value: 'no', label: 'No, I prefer to work with what I have' },
      { value: 'maybe', label: 'Maybe, depends on the certification' },
    ],
    required: true,
  },
];

export function getQuestionsByCategory(category: CareerQuestion['category']): CareerQuestion[] {
  return careerQuestionnaire.filter(q => q.category === category);
}

export function getRequiredQuestions(): CareerQuestion[] {
  return careerQuestionnaire.filter(q => q.required);
}

export function getCategoryProgress(responses: Record<string, unknown>, category: CareerQuestion['category']): number {
  const categoryQuestions = getQuestionsByCategory(category);
  const answeredCount = categoryQuestions.filter(q => responses[q.id] !== undefined).length;
  return categoryQuestions.length > 0 ? (answeredCount / categoryQuestions.length) * 100 : 0;
}