import { JobCategory } from '@/types/career';

export const designRoles: JobCategory[] = [
  {
    id: 'ux-ui-designer',
    category: 'design',
    title: 'UX/UI Designer',
    description: 'UX/UI Designers create intuitive and visually appealing digital interfaces by researching user needs, designing wireframes and prototypes, and collaborating with development teams to deliver seamless user experiences.',
    alternativeTitles: ['Product Designer', 'User Experience Designer', 'Interface Designer', 'Digital Designer'],
    dailyTasks: [
      { task: 'Conduct user research and analyze feedback', frequency: 'daily', timePercentage: 15 },
      { task: 'Create wireframes and interactive prototypes', frequency: 'daily', timePercentage: 25 },
      { task: 'Design UI components and visual elements', frequency: 'daily', timePercentage: 20 },
      { task: 'Collaborate with developers and product managers', frequency: 'daily', timePercentage: 15 },
      { task: 'Conduct usability testing and iterate designs', frequency: 'weekly', timePercentage: 10 },
      { task: 'Maintain design systems and documentation', frequency: 'daily', timePercentage: 10 },
      { task: 'Present design concepts to stakeholders', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Figma', category: 'technical', importance: 'required', description: 'Industry-standard design and prototyping tool' },
      { skill: 'Adobe XD', category: 'technical', importance: 'preferred' },
      { skill: 'Sketch', category: 'technical', importance: 'preferred' },
      { skill: 'User research methods', category: 'technical', importance: 'required' },
      { skill: 'Wireframing and prototyping', category: 'technical', importance: 'required' },
      { skill: 'Design systems', category: 'technical', importance: 'required' },
      { skill: 'HTML/CSS basics', category: 'technical', importance: 'preferred' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Problem-solving', category: 'soft', importance: 'required' },
      { skill: 'Empathy', category: 'soft', importance: 'required' },
      { skill: 'Collaboration', category: 'soft', importance: 'required' },
      { skill: 'Google UX Design Certificate', category: 'certification', importance: 'nice-to-have' },
      { skill: 'Nielsen Norman Group UX Certificate', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 65000, max: 85000, median: 75000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 85000, max: 115000, median: 100000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 110000, max: 150000, median: 130000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Junior UX/UI Designer',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 65000, max: 85000, median: 75000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Create wireframes and mockups', 'Assist with user research', 'Design UI components', 'Learn design systems'],
        requiredSkills: ['Figma proficiency', 'Basic UX principles', 'Visual design skills'],
      },
      {
        level: 'mid',
        title: 'UX/UI Designer',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 85000, max: 115000, median: 100000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Lead design projects', 'Conduct user research', 'Build design systems', 'Mentor junior designers'],
        requiredSkills: ['Advanced prototyping', 'User testing', 'Design system management', 'Cross-functional collaboration'],
      },
      {
        level: 'senior',
        title: 'Senior UX/UI Designer',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 110000, max: 150000, median: 130000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Define design strategy', 'Lead complex projects', 'Establish design standards', 'Guide team members'],
        requiredSkills: ['Design leadership', 'Strategic thinking', 'Advanced UX methodologies', 'Stakeholder management'],
      },
      {
        level: 'executive',
        title: 'Lead Product Designer / Design Manager',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 140000, max: 200000, median: 170000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Manage design teams', 'Set product vision', 'Drive design culture', 'Strategic planning'],
        requiredSkills: ['Team leadership', 'Business strategy', 'Design operations', 'Executive communication'],
      },
    ],
    industryInsights: [
      {
        topic: 'AI integration in design',
        description: 'Growing use of AI tools for design automation and enhancement, requiring designers to adapt',
        trend: 'growing',
      },
      {
        topic: 'Design systems maturity',
        description: 'Companies investing heavily in comprehensive design systems for consistency and efficiency',
        trend: 'growing',
      },
      {
        topic: 'Accessibility focus',
        description: 'Increased emphasis on inclusive design and WCAG compliance',
        trend: 'growing',
      },
      {
        topic: 'Remote design work',
        description: 'Continued strong demand for remote and hybrid UX/UI positions',
        trend: 'stable',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, flexible schedules common',
    },
    jobOutlook: {
      growthRate: '16% (2022-2032, much faster than average)',
      projectedJobs: '23,900 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: 'Bachelor\'s degree in Design, HCI, or related field',
      preferredDegree: 'Bachelor\'s or Master\'s in UX Design, Interaction Design, or HCI',
      certifications: ['Google UX Design Professional Certificate', 'Nielsen Norman Group UX Certification', 'Interaction Design Foundation Certificate'],
      alternativePathways: ['UX bootcamps', 'Self-taught with strong portfolio', 'Career switchers from graphic design or development'],
    },
    relatedRoles: ['Product Designer', 'Interaction Designer', 'UX Researcher', 'Visual Designer', 'UI Developer'],
    keywords: ['ux design', 'ui design', 'user experience', 'figma', 'prototyping', 'wireframes', 'user research', 'design systems'],
  },
  {
    id: 'graphic-designer',
    category: 'design',
    title: 'Graphic Designer',
    description: 'Graphic Designers create visual concepts using computer software or by hand to communicate ideas that inspire, inform, and captivate consumers. They develop layouts and designs for advertisements, brochures, magazines, and corporate reports.',
    alternativeTitles: ['Visual Designer', 'Communication Designer', 'Creative Designer', 'Production Designer'],
    dailyTasks: [
      { task: 'Create visual designs for print and digital media', frequency: 'daily', timePercentage: 30 },
      { task: 'Meet with clients to understand project requirements', frequency: 'daily', timePercentage: 15 },
      { task: 'Design layouts using Adobe Creative Suite', frequency: 'daily', timePercentage: 25 },
      { task: 'Develop design concepts and present to stakeholders', frequency: 'weekly', timePercentage: 10 },
      { task: 'Review and refine designs based on feedback', frequency: 'daily', timePercentage: 10 },
      { task: 'Prepare files for production and printing', frequency: 'daily', timePercentage: 5 },
      { task: 'Stay updated on design trends and techniques', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Adobe Photoshop', category: 'technical', importance: 'required', description: 'Essential for image editing and manipulation' },
      { skill: 'Adobe Illustrator', category: 'technical', importance: 'required' },
      { skill: 'Adobe InDesign', category: 'technical', importance: 'required' },
      { skill: 'Typography', category: 'technical', importance: 'required' },
      { skill: 'Color theory', category: 'technical', importance: 'required' },
      { skill: 'Layout design', category: 'technical', importance: 'required' },
      { skill: 'Print production', category: 'technical', importance: 'preferred' },
      { skill: 'Figma', category: 'technical', importance: 'preferred' },
      { skill: 'Creativity', category: 'soft', importance: 'required' },
      { skill: 'Time management', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Attention to detail', category: 'soft', importance: 'required' },
      { skill: 'Adobe Certified Professional', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 42000, max: 55000, median: 48500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 52000, max: 70000, median: 61000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 65000, max: 90000, median: 77500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Junior Graphic Designer',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 42000, max: 55000, median: 48500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Create basic designs', 'Assist senior designers', 'Learn design processes', 'Execute production tasks'],
        requiredSkills: ['Adobe Creative Suite', 'Basic design principles', 'File preparation'],
      },
      {
        level: 'mid',
        title: 'Graphic Designer',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 52000, max: 70000, median: 61000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Lead design projects', 'Client communication', 'Concept development', 'Multi-platform design'],
        requiredSkills: ['Advanced Adobe skills', 'Brand development', 'Project management', 'Client relations'],
      },
      {
        level: 'senior',
        title: 'Senior Graphic Designer',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 65000, max: 90000, median: 77500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Art direction', 'Team mentorship', 'Brand strategy', 'Complex campaign design'],
        requiredSkills: ['Art direction', 'Strategic thinking', 'Team leadership', 'Portfolio of major projects'],
      },
      {
        level: 'executive',
        title: 'Art Director / Creative Director',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 85000, max: 130000, median: 107500, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Creative vision', 'Team management', 'Client strategy', 'Business development'],
        requiredSkills: ['Leadership', 'Business acumen', 'Strategic planning', 'Creative direction'],
      },
    ],
    industryInsights: [
      {
        topic: 'Digital skills demand',
        description: 'Increasing need for designers with motion graphics and web design capabilities',
        trend: 'growing',
      },
      {
        topic: 'Freelance opportunities',
        description: 'Growing gig economy providing flexible work options for graphic designers',
        trend: 'growing',
      },
      {
        topic: 'Print design decline',
        description: 'Traditional print media jobs decreasing as digital media expands',
        trend: 'declining',
      },
      {
        topic: 'AI design tools',
        description: 'Emergence of AI-assisted design tools changing workflow and efficiency',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, occasional overtime for deadlines',
    },
    jobOutlook: {
      growthRate: '3% (2022-2032, about as fast as average)',
      projectedJobs: '24,800 openings per year',
      competitionLevel: 'high',
    },
    education: {
      minimumDegree: 'Associate degree in Graphic Design',
      preferredDegree: 'Bachelor\'s degree in Graphic Design or Visual Communications',
      certifications: ['Adobe Certified Professional', 'Apple Certified Pro', 'Certified Graphic Designer (CGD)'],
      alternativePathways: ['Self-taught with strong portfolio', 'Design bootcamps', 'Online courses and certifications'],
    },
    relatedRoles: ['Art Director', 'Brand Designer', 'Web Designer', 'Marketing Designer', 'Production Artist'],
    keywords: ['graphic design', 'adobe creative suite', 'visual design', 'branding', 'print design', 'digital design', 'illustrator', 'photoshop'],
  },
  {
    id: 'visual-merchandiser',
    category: 'design',
    title: 'Visual Merchandiser',
    description: 'Visual Merchandisers design and arrange product displays in retail stores to maximize sales and create appealing shopping experiences. They combine creativity with marketing strategy to showcase products effectively.',
    alternativeTitles: ['Merchandise Display Designer', 'Store Designer', 'Display Coordinator', 'VM Specialist'],
    dailyTasks: [
      { task: 'Create and install window and in-store displays', frequency: 'daily', timePercentage: 25 },
      { task: 'Plan merchandising strategies and layouts', frequency: 'weekly', timePercentage: 15 },
      { task: 'Arrange products to maximize visual impact', frequency: 'daily', timePercentage: 20 },
      { task: 'Collaborate with buyers and store managers', frequency: 'daily', timePercentage: 10 },
      { task: 'Monitor sales data and adjust displays accordingly', frequency: 'weekly', timePercentage: 10 },
      { task: 'Source props and display materials', frequency: 'weekly', timePercentage: 10 },
      { task: 'Maintain brand consistency across locations', frequency: 'daily', timePercentage: 10 },
    ],
    requiredSkills: [
      { skill: 'Visual design principles', category: 'technical', importance: 'required', description: 'Understanding of composition, color, and spatial arrangement' },
      { skill: 'Retail merchandising', category: 'technical', importance: 'required' },
      { skill: 'Space planning', category: 'technical', importance: 'required' },
      { skill: 'Adobe Creative Suite', category: 'technical', importance: 'preferred' },
      { skill: 'SketchUp or CAD', category: 'technical', importance: 'preferred' },
      { skill: 'Lighting design', category: 'technical', importance: 'preferred' },
      { skill: 'Creativity', category: 'soft', importance: 'required' },
      { skill: 'Physical stamina', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Trend awareness', category: 'soft', importance: 'required' },
      { skill: 'Project management', category: 'soft', importance: 'preferred' },
      { skill: 'Certified Visual Merchandiser', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 38000, max: 48000, median: 43000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 45000, max: 60000, median: 52500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 55000, max: 75000, median: 65000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Visual Merchandiser Assistant',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 38000, max: 48000, median: 43000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Install displays', 'Maintain visual standards', 'Assist with props', 'Update signage'],
        requiredSkills: ['Basic design principles', 'Physical work', 'Attention to detail'],
      },
      {
        level: 'mid',
        title: 'Visual Merchandiser',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 45000, max: 60000, median: 52500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Design displays', 'Manage multiple stores', 'Analyze sales impact', 'Train staff'],
        requiredSkills: ['Advanced visual design', 'Data analysis', 'Multi-store coordination', 'Team training'],
      },
      {
        level: 'senior',
        title: 'Senior Visual Merchandiser',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 55000, max: 75000, median: 65000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Regional oversight', 'Strategic planning', 'Team leadership', 'Budget management'],
        requiredSkills: ['Leadership', 'Strategic thinking', 'Budget management', 'Regional coordination'],
      },
      {
        level: 'executive',
        title: 'Visual Merchandising Manager / Director',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 70000, max: 100000, median: 85000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Company-wide VM strategy', 'Department management', 'Brand standards', 'Executive reporting'],
        requiredSkills: ['Executive leadership', 'Strategic planning', 'Business operations', 'Brand management'],
      },
    ],
    industryInsights: [
      {
        topic: 'E-commerce integration',
        description: 'Growing need to connect physical displays with online shopping experiences',
        trend: 'growing',
      },
      {
        topic: 'Sustainable displays',
        description: 'Increasing focus on eco-friendly materials and reusable display elements',
        trend: 'growing',
      },
      {
        topic: 'Experiential retail',
        description: 'Shift toward creating immersive, Instagram-worthy shopping experiences',
        trend: 'growing',
      },
      {
        topic: 'Retail consolidation',
        description: 'Store closures affecting traditional VM roles but creating specialized opportunities',
        trend: 'stable',
      },
    ],
    workEnvironment: {
      remote: false,
      hybrid: false,
      onsite: true,
      travelRequired: true,
      typicalHours: '40+ hours per week, including weekends and evenings for installations',
    },
    jobOutlook: {
      growthRate: '2% (2022-2032, slower than average)',
      projectedJobs: '9,200 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: 'High school diploma or equivalent',
      preferredDegree: 'Associate or Bachelor\'s degree in Visual Merchandising, Fashion, or Design',
      certifications: ['Certified Visual Merchandiser (CVM)', 'Retail Design Professional Certificate'],
      alternativePathways: ['Fashion merchandising programs', 'Interior design background', 'On-the-job training in retail'],
    },
    relatedRoles: ['Store Designer', 'Retail Buyer', 'Marketing Coordinator', 'Interior Designer', 'Event Designer'],
    keywords: ['visual merchandising', 'retail design', 'store displays', 'merchandising', 'window display', 'product presentation', 'retail'],
  },
  {
    id: 'brand-designer',
    category: 'design',
    title: 'Brand Designer',
    description: 'Brand Designers create and maintain visual identities for companies and products, developing logos, color palettes, typography systems, and brand guidelines that communicate a company\'s values and personality across all touchpoints.',
    alternativeTitles: ['Brand Identity Designer', 'Identity Designer', 'Brand Specialist', 'Visual Brand Designer'],
    dailyTasks: [
      { task: 'Develop brand identity systems and guidelines', frequency: 'daily', timePercentage: 25 },
      { task: 'Design logos and visual brand elements', frequency: 'daily', timePercentage: 20 },
      { task: 'Create brand collateral and marketing materials', frequency: 'daily', timePercentage: 20 },
      { task: 'Conduct brand research and competitive analysis', frequency: 'weekly', timePercentage: 10 },
      { task: 'Collaborate with marketing and creative teams', frequency: 'daily', timePercentage: 15 },
      { task: 'Present brand concepts to clients and stakeholders', frequency: 'weekly', timePercentage: 5 },
      { task: 'Ensure brand consistency across all platforms', frequency: 'daily', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Adobe Illustrator', category: 'technical', importance: 'required', description: 'Primary tool for logo and brand design' },
      { skill: 'Adobe Photoshop', category: 'technical', importance: 'required' },
      { skill: 'Adobe InDesign', category: 'technical', importance: 'required' },
      { skill: 'Brand strategy', category: 'technical', importance: 'required' },
      { skill: 'Typography', category: 'technical', importance: 'required' },
      { skill: 'Logo design', category: 'technical', importance: 'required' },
      { skill: 'Color theory', category: 'technical', importance: 'required' },
      { skill: 'Figma', category: 'technical', importance: 'preferred' },
      { skill: 'Strategic thinking', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Creativity', category: 'soft', importance: 'required' },
      { skill: 'Attention to detail', category: 'soft', importance: 'required' },
      { skill: 'Presentation skills', category: 'soft', importance: 'required' },
    ],
    salaryRanges: [
      { min: 55000, max: 70000, median: 62500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 70000, max: 95000, median: 82500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 90000, max: 125000, median: 107500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Junior Brand Designer',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 55000, max: 70000, median: 62500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Design brand assets', 'Assist with brand guidelines', 'Create marketing materials', 'Learn brand strategy'],
        requiredSkills: ['Adobe Creative Suite', 'Design fundamentals', 'Brand awareness'],
      },
      {
        level: 'mid',
        title: 'Brand Designer',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 70000, max: 95000, median: 82500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Lead brand projects', 'Develop brand strategies', 'Create comprehensive guidelines', 'Client presentations'],
        requiredSkills: ['Brand strategy', 'Advanced design skills', 'Client management', 'Presentation expertise'],
      },
      {
        level: 'senior',
        title: 'Senior Brand Designer',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 90000, max: 125000, median: 107500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Define brand strategy', 'Lead rebranding projects', 'Mentor design team', 'Cross-department leadership'],
        requiredSkills: ['Strategic leadership', 'Advanced brand strategy', 'Team mentorship', 'Business acumen'],
      },
      {
        level: 'executive',
        title: 'Brand Design Director / Creative Director',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 115000, max: 170000, median: 142500, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Company brand vision', 'Department management', 'Executive strategy', 'Agency partnerships'],
        requiredSkills: ['Executive leadership', 'Business strategy', 'Team management', 'Brand portfolio oversight'],
      },
    ],
    industryInsights: [
      {
        topic: 'Brand experience design',
        description: 'Growing demand for designers who can create holistic brand experiences across touchpoints',
        trend: 'growing',
      },
      {
        topic: 'Motion branding',
        description: 'Increasing need for animated logos and dynamic brand elements',
        trend: 'growing',
      },
      {
        topic: 'Sustainable branding',
        description: 'Focus on eco-conscious brand values and authentic purpose-driven design',
        trend: 'growing',
      },
      {
        topic: 'Personal branding',
        description: 'Growing market for individual and small business branding services',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, occasional overtime for major launches',
    },
    jobOutlook: {
      growthRate: '4% (2022-2032, about as fast as average)',
      projectedJobs: '18,500 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: 'Associate degree in Graphic Design or related field',
      preferredDegree: 'Bachelor\'s degree in Graphic Design, Branding, or Visual Communications',
      certifications: ['Adobe Certified Professional', 'Brand Management Certificate', 'Digital Marketing Certificate'],
      alternativePathways: ['Portfolio-based hiring', 'Graphic design to branding specialization', 'Marketing background with design skills'],
    },
    relatedRoles: ['Graphic Designer', 'Art Director', 'Marketing Designer', 'Creative Director', 'Brand Strategist'],
    keywords: ['brand design', 'brand identity', 'logo design', 'branding', 'visual identity', 'brand guidelines', 'brand strategy'],
  },
  {
    id: 'marketing-designer',
    category: 'design',
    title: 'Marketing Designer',
    description: 'Marketing Designers create visual content for marketing campaigns across digital and print channels, including social media graphics, email templates, landing pages, advertisements, and promotional materials that drive engagement and conversions.',
    alternativeTitles: ['Marketing Graphic Designer', 'Digital Marketing Designer', 'Campaign Designer', 'Growth Designer'],
    dailyTasks: [
      { task: 'Design social media graphics and ad campaigns', frequency: 'daily', timePercentage: 25 },
      { task: 'Create email templates and landing page designs', frequency: 'daily', timePercentage: 20 },
      { task: 'Develop marketing collateral and promotional materials', frequency: 'daily', timePercentage: 20 },
      { task: 'Collaborate with marketing team on campaign strategy', frequency: 'daily', timePercentage: 15 },
      { task: 'Analyze performance metrics and iterate designs', frequency: 'weekly', timePercentage: 10 },
      { task: 'Maintain brand consistency across channels', frequency: 'daily', timePercentage: 5 },
      { task: 'Stay current on design and marketing trends', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Adobe Creative Suite', category: 'technical', importance: 'required', description: 'Photoshop, Illustrator, InDesign for marketing materials' },
      { skill: 'Figma', category: 'technical', importance: 'required' },
      { skill: 'Canva', category: 'technical', importance: 'preferred' },
      { skill: 'Social media design', category: 'technical', importance: 'required' },
      { skill: 'Email design', category: 'technical', importance: 'required' },
      { skill: 'HTML/CSS basics', category: 'technical', importance: 'preferred' },
      { skill: 'Motion graphics', category: 'technical', importance: 'preferred' },
      { skill: 'Marketing analytics', category: 'technical', importance: 'preferred' },
      { skill: 'Creativity', category: 'soft', importance: 'required' },
      { skill: 'Fast execution', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Data-driven thinking', category: 'soft', importance: 'required' },
      { skill: 'Multitasking', category: 'soft', importance: 'required' },
      { skill: 'Google Analytics Certification', category: 'certification', importance: 'nice-to-have' },
      { skill: 'HubSpot Design Certification', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 50000, max: 65000, median: 57500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 62000, max: 82000, median: 72000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 78000, max: 105000, median: 91500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Junior Marketing Designer',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 50000, max: 65000, median: 57500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Create social graphics', 'Design email templates', 'Support campaigns', 'Resize assets'],
        requiredSkills: ['Adobe Creative Suite', 'Social media platforms', 'Basic marketing knowledge'],
      },
      {
        level: 'mid',
        title: 'Marketing Designer',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 62000, max: 82000, median: 72000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Lead campaign design', 'A/B testing', 'Multi-channel campaigns', 'Performance optimization'],
        requiredSkills: ['Advanced design skills', 'Marketing strategy', 'Analytics understanding', 'Campaign management'],
      },
      {
        level: 'senior',
        title: 'Senior Marketing Designer',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 78000, max: 105000, median: 91500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Marketing design strategy', 'Team leadership', 'Brand evolution', 'Cross-functional collaboration'],
        requiredSkills: ['Strategic design', 'Team leadership', 'Data analysis', 'Marketing expertise'],
      },
      {
        level: 'executive',
        title: 'Marketing Design Manager / Creative Lead',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 95000, max: 140000, median: 117500, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Team management', 'Marketing creative strategy', 'Budget management', 'Executive reporting'],
        requiredSkills: ['Leadership', 'Business strategy', 'Team development', 'Marketing operations'],
      },
    ],
    industryInsights: [
      {
        topic: 'Performance marketing focus',
        description: 'Increasing emphasis on data-driven design decisions and conversion optimization',
        trend: 'growing',
      },
      {
        topic: 'Video and motion content',
        description: 'Growing demand for designers with motion graphics and video editing skills',
        trend: 'growing',
      },
      {
        topic: 'Multi-channel expertise',
        description: 'Need to design consistently across diverse digital and traditional channels',
        trend: 'stable',
      },
      {
        topic: 'AI marketing tools',
        description: 'Integration of AI tools for faster asset creation and personalization',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, occasional overtime for campaign launches',
    },
    jobOutlook: {
      growthRate: '8% (2022-2032, faster than average)',
      projectedJobs: '21,300 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: 'Associate degree in Graphic Design or Marketing',
      preferredDegree: 'Bachelor\'s degree in Graphic Design, Marketing, or Communications',
      certifications: ['Google Analytics Certification', 'HubSpot Content Marketing', 'Facebook Blueprint Certification', 'Adobe Certified Professional'],
      alternativePathways: ['Marketing background transitioning to design', 'Graphic design with marketing specialization', 'Self-taught with strong portfolio'],
    },
    relatedRoles: ['Graphic Designer', 'Social Media Designer', 'Digital Designer', 'Growth Designer', 'Brand Designer'],
    keywords: ['marketing design', 'digital marketing', 'social media design', 'campaign design', 'email design', 'advertising design', 'growth design'],
  },
  {
    id: 'creative-director',
    category: 'design',
    title: 'Creative Director',
    description: 'Creative Directors lead and oversee the creative vision and output for agencies, brands, or in-house teams. They manage designers, copywriters, and other creatives while guiding projects from concept to execution and ensuring high-quality creative work.',
    alternativeTitles: ['Design Director', 'Executive Creative Director', 'Chief Creative Officer', 'Head of Creative'],
    dailyTasks: [
      { task: 'Develop creative strategy and vision for campaigns', frequency: 'daily', timePercentage: 20 },
      { task: 'Lead and mentor creative team members', frequency: 'daily', timePercentage: 20 },
      { task: 'Present creative concepts to clients and executives', frequency: 'weekly', timePercentage: 15 },
      { task: 'Review and approve creative work', frequency: 'daily', timePercentage: 15 },
      { task: 'Collaborate with account management and strategy teams', frequency: 'daily', timePercentage: 10 },
      { task: 'Participate in new business pitches', frequency: 'weekly', timePercentage: 10 },
      { task: 'Manage budgets and resources', frequency: 'weekly', timePercentage: 10 },
    ],
    requiredSkills: [
      { skill: 'Creative leadership', category: 'technical', importance: 'required', description: 'Ability to guide creative vision and inspire teams' },
      { skill: 'Art direction', category: 'technical', importance: 'required' },
      { skill: 'Design expertise', category: 'technical', importance: 'required' },
      { skill: 'Brand strategy', category: 'technical', importance: 'required' },
      { skill: 'Campaign development', category: 'technical', importance: 'required' },
      { skill: 'Adobe Creative Suite', category: 'technical', importance: 'preferred' },
      { skill: 'Leadership', category: 'soft', importance: 'required' },
      { skill: 'Strategic thinking', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Client relations', category: 'soft', importance: 'required' },
      { skill: 'Team management', category: 'soft', importance: 'required' },
      { skill: 'Business acumen', category: 'soft', importance: 'required' },
      { skill: 'Presentation skills', category: 'soft', importance: 'required' },
    ],
    salaryRanges: [
      { min: 95000, max: 130000, median: 112500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 120000, max: 165000, median: 142500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 150000, max: 220000, median: 185000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Associate Creative Director',
        yearsExperience: '8-10 years',
        typicalSalaryRange: { min: 95000, max: 130000, median: 112500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Support creative direction', 'Lead smaller teams', 'Oversee specific projects', 'Develop creative concepts'],
        requiredSkills: ['Strong portfolio', 'Team leadership', 'Art direction', 'Client presentation'],
      },
      {
        level: 'mid',
        title: 'Creative Director',
        yearsExperience: '10-15 years',
        typicalSalaryRange: { min: 120000, max: 165000, median: 142500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Full creative leadership', 'Team management', 'Client relationships', 'Strategic planning'],
        requiredSkills: ['Extensive portfolio', 'Strategic leadership', 'Business development', 'Team development'],
      },
      {
        level: 'senior',
        title: 'Senior Creative Director',
        yearsExperience: '15-20 years',
        typicalSalaryRange: { min: 150000, max: 220000, median: 185000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Multi-team oversight', 'Agency/brand vision', 'Key client relationships', 'New business development'],
        requiredSkills: ['Award-winning work', 'Executive leadership', 'Business strategy', 'Industry reputation'],
      },
      {
        level: 'executive',
        title: 'Executive Creative Director / Chief Creative Officer',
        yearsExperience: '20+ years',
        typicalSalaryRange: { min: 180000, max: 300000, median: 240000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Company-wide creative vision', 'Executive leadership', 'Major client partnerships', 'Agency positioning'],
        requiredSkills: ['Executive leadership', 'Industry influence', 'Business operations', 'Organizational strategy'],
      },
    ],
    industryInsights: [
      {
        topic: 'Integrated campaigns',
        description: 'Growing need for directors who understand multi-platform, integrated creative approaches',
        trend: 'growing',
      },
      {
        topic: 'In-house creative teams',
        description: 'More brands building internal creative departments, creating new CD opportunities',
        trend: 'growing',
      },
      {
        topic: 'Digital-first leadership',
        description: 'Increasing importance of digital and social media expertise for creative leaders',
        trend: 'growing',
      },
      {
        topic: 'Diverse skill sets',
        description: 'CDs expected to understand design, copy, strategy, and emerging technologies',
        trend: 'stable',
      },
    ],
    workEnvironment: {
      remote: false,
      hybrid: true,
      onsite: true,
      travelRequired: true,
      typicalHours: '50+ hours per week, including client meetings and pitches',
    },
    jobOutlook: {
      growthRate: '4% (2022-2032, about as fast as average)',
      projectedJobs: '6,700 openings per year',
      competitionLevel: 'high',
    },
    education: {
      minimumDegree: 'Bachelor\'s degree in Design, Advertising, or related field',
      preferredDegree: 'Bachelor\'s or Master\'s in Design, Advertising, or Fine Arts with extensive portfolio',
      certifications: ['Portfolio of award-winning work', 'Industry recognition (Cannes Lions, D&AD, One Show)', 'Leadership training programs'],
      alternativePathways: ['Promoted from senior designer/art director', 'Agency to in-house transition', 'Entrepreneurial creative background'],
    },
    relatedRoles: ['Art Director', 'Design Director', 'Brand Director', 'VP of Creative', 'Chief Creative Officer'],
    keywords: ['creative director', 'art direction', 'creative leadership', 'campaign strategy', 'team management', 'brand vision', 'creative strategy'],
  },
];