import { JobCategory } from '@/types/career';

export const financeRoles: JobCategory[] = [
  {
    id: 'financial-analyst',
    category: 'finance',
    title: 'Financial Analyst',
    description: 'Financial Analysts evaluate investment opportunities, analyze financial data, create forecasts, and provide recommendations to support business decisions and strategic planning.',
    alternativeTitles: ['Finance Analyst', 'Investment Analyst', 'Business Analyst - Finance', 'Corporate Financial Analyst'],
    dailyTasks: [
      { task: 'Analyze financial statements and reports', frequency: 'daily', timePercentage: 25 },
      { task: 'Create financial models and forecasts', frequency: 'daily', timePercentage: 20 },
      { task: 'Prepare presentations and reports for management', frequency: 'daily', timePercentage: 15 },
      { task: 'Monitor market trends and economic indicators', frequency: 'daily', timePercentage: 15 },
      { task: 'Conduct variance analysis and budget tracking', frequency: 'daily', timePercentage: 10 },
      { task: 'Collaborate with cross-functional teams', frequency: 'daily', timePercentage: 10 },
      { task: 'Research investment opportunities', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Financial modeling', category: 'technical', importance: 'required', description: 'Advanced Excel and financial modeling' },
      { skill: 'Excel (advanced)', category: 'technical', importance: 'required' },
      { skill: 'Financial statement analysis', category: 'technical', importance: 'required' },
      { skill: 'Accounting principles (GAAP)', category: 'technical', importance: 'required' },
      { skill: 'Data analysis', category: 'technical', importance: 'required' },
      { skill: 'SQL', category: 'technical', importance: 'preferred' },
      { skill: 'PowerPoint and presentation skills', category: 'technical', importance: 'preferred' },
      { skill: 'ERP systems (SAP, Oracle)', category: 'technical', importance: 'preferred' },
      { skill: 'Python or R', category: 'technical', importance: 'nice-to-have' },
      { skill: 'Analytical thinking', category: 'soft', importance: 'required' },
      { skill: 'Attention to detail', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Problem-solving', category: 'soft', importance: 'required' },
      { skill: 'Time management', category: 'soft', importance: 'required' },
      { skill: 'CFA Level I', category: 'certification', importance: 'preferred' },
      { skill: 'FMVA (Financial Modeling & Valuation Analyst)', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 60000, max: 75000, median: 67500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 75000, max: 95000, median: 85000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 95000, max: 130000, median: 112500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Junior Financial Analyst',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 60000, max: 75000, median: 67500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Financial reporting', 'Data gathering', 'Basic analysis', 'Report preparation'],
        requiredSkills: ['Excel', 'Financial statements', 'Basic accounting', 'Attention to detail'],
      },
      {
        level: 'mid',
        title: 'Financial Analyst',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 75000, max: 95000, median: 85000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Financial modeling', 'Forecasting', 'Variance analysis', 'Strategic recommendations'],
        requiredSkills: ['Advanced modeling', 'Forecasting', 'Business understanding', 'Presentation skills'],
      },
      {
        level: 'senior',
        title: 'Senior Financial Analyst',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 95000, max: 130000, median: 112500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Complex modeling', 'Strategic planning', 'Team leadership', 'Executive presentations'],
        requiredSkills: ['Expert modeling', 'Strategic thinking', 'Leadership', 'Business partnership'],
      },
      {
        level: 'executive',
        title: 'Finance Manager / Director of FP&A',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 130000, max: 180000, median: 155000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Financial strategy', 'Team management', 'Budget planning', 'Executive advisory'],
        requiredSkills: ['Strategic leadership', 'Team building', 'Executive communication', 'Business acumen'],
      },
    ],
    industryInsights: [
      {
        topic: 'Data analytics tools',
        description: 'Growing use of Python, Tableau, and Power BI for financial analysis',
        trend: 'growing',
      },
      {
        topic: 'FP&A automation',
        description: 'Automation and AI reducing manual reporting, increasing strategic focus',
        trend: 'growing',
      },
      {
        topic: 'Business partnering',
        description: 'Shift from reporting role to strategic business advisor',
        trend: 'stable',
      },
      {
        topic: 'ESG integration',
        description: 'Environmental, Social, and Governance factors in financial analysis',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40-50 hours per week, busy during month/quarter/year-end',
    },
    jobOutlook: {
      growthRate: '9% (2021-2031, as fast as average)',
      projectedJobs: '41,000 openings per year',
      competitionLevel: 'high',
    },
    education: {
      minimumDegree: 'Bachelor of Science in Finance, Accounting, Economics, or Business',
      preferredDegree: 'Bachelor\'s with CFA or MBA',
      certifications: ['CFA (Chartered Financial Analyst)', 'FMVA', 'CPA', 'Financial Risk Manager (FRM)'],
      alternativePathways: ['Accounting to finance transition', 'Financial modeling bootcamps', 'Internal company transitions', 'Big 4 accounting firms'],
    },
    relatedRoles: ['Investment Analyst', 'Budget Analyst', 'FP&A Analyst', 'Business Analyst', 'Equity Research Analyst'],
    keywords: ['financial analyst', 'FP&A', 'financial modeling', 'forecasting', 'budgeting', 'analysis', 'finance'],
  },
  {
    id: 'accountant',
    category: 'finance',
    title: 'Accountant',
    description: 'Accountants prepare and examine financial records, ensure accuracy and compliance with regulations, prepare tax returns, and provide financial guidance to organizations and individuals.',
    alternativeTitles: ['Staff Accountant', 'Public Accountant', 'Corporate Accountant', 'General Accountant'],
    dailyTasks: [
      { task: 'Record and maintain financial transactions', frequency: 'daily', timePercentage: 25 },
      { task: 'Prepare journal entries and reconciliations', frequency: 'daily', timePercentage: 20 },
      { task: 'Review financial statements for accuracy', frequency: 'daily', timePercentage: 15 },
      { task: 'Assist with month-end and year-end close', frequency: 'daily', timePercentage: 15 },
      { task: 'Ensure compliance with accounting standards', frequency: 'daily', timePercentage: 10 },
      { task: 'Collaborate with auditors and tax professionals', frequency: 'weekly', timePercentage: 10 },
      { task: 'Prepare tax documents and filings', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'GAAP accounting principles', category: 'technical', importance: 'required', description: 'Accounting standards expertise' },
      { skill: 'Accounting software (QuickBooks, NetSuite, SAP)', category: 'technical', importance: 'required' },
      { skill: 'Excel (advanced)', category: 'technical', importance: 'required' },
      { skill: 'Financial statement preparation', category: 'technical', importance: 'required' },
      { skill: 'Account reconciliation', category: 'technical', importance: 'required' },
      { skill: 'Tax preparation', category: 'technical', importance: 'preferred' },
      { skill: 'Audit procedures', category: 'technical', importance: 'preferred' },
      { skill: 'ERP systems', category: 'technical', importance: 'preferred' },
      { skill: 'Attention to detail', category: 'soft', importance: 'required' },
      { skill: 'Analytical thinking', category: 'soft', importance: 'required' },
      { skill: 'Integrity', category: 'soft', importance: 'required' },
      { skill: 'Time management', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'CPA (Certified Public Accountant)', category: 'certification', importance: 'preferred' },
      { skill: 'CMA (Certified Management Accountant)', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 50000, max: 62000, median: 56000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 62000, max: 80000, median: 71000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 80000, max: 105000, median: 92500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Junior Accountant / Staff Accountant',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 50000, max: 62000, median: 56000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Journal entries', 'Reconciliations', 'Data entry', 'Basic reporting'],
        requiredSkills: ['GAAP basics', 'Accounting software', 'Excel', 'Attention to detail'],
      },
      {
        level: 'mid',
        title: 'Accountant',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 62000, max: 80000, median: 71000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Financial statements', 'Month-end close', 'Tax preparation', 'Process improvement'],
        requiredSkills: ['Advanced GAAP', 'Complex reconciliations', 'Tax knowledge', 'CPA progress'],
      },
      {
        level: 'senior',
        title: 'Senior Accountant',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 80000, max: 105000, median: 92500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Accounting supervision', 'Complex transactions', 'Audit coordination', 'Team mentoring'],
        requiredSkills: ['CPA certification', 'Leadership', 'Advanced accounting', 'Audit experience'],
      },
      {
        level: 'executive',
        title: 'Accounting Manager / Controller',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 105000, max: 150000, median: 127500, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Department management', 'Financial reporting', 'Internal controls', 'Strategic planning'],
        requiredSkills: ['CPA certification', 'Leadership', 'Strategic planning', 'Team management'],
      },
    ],
    industryInsights: [
      {
        topic: 'Accounting automation',
        description: 'AI and automation tools reducing manual bookkeeping tasks',
        trend: 'growing',
      },
      {
        topic: 'Cloud accounting',
        description: 'Widespread adoption of cloud-based accounting platforms',
        trend: 'stable',
      },
      {
        topic: 'Advisory services growth',
        description: 'Accountants shifting from compliance to advisory and strategic roles',
        trend: 'growing',
      },
      {
        topic: 'Continuous close',
        description: 'Move toward real-time accounting and faster close processes',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40-50 hours per week, longer during busy season',
    },
    jobOutlook: {
      growthRate: '6% (2021-2031, as fast as average)',
      projectedJobs: '136,400 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: 'Bachelor of Science in Accounting or Finance',
      preferredDegree: 'Bachelor\'s with 150 credits for CPA eligibility',
      certifications: ['CPA (Certified Public Accountant)', 'CMA (Certified Management Accountant)', 'EA (Enrolled Agent)'],
      alternativePathways: ['Big 4 accounting firms', 'Community college to bachelor\'s', 'Bookkeeper to accountant', 'Military finance to civilian accounting'],
    },
    relatedRoles: ['Auditor', 'Tax Accountant', 'Cost Accountant', 'Bookkeeper', 'Controller'],
    keywords: ['accountant', 'accounting', 'CPA', 'GAAP', 'financial statements', 'bookkeeping', 'reconciliation'],
  },
  {
    id: 'financial-advisor',
    category: 'finance',
    title: 'Financial Advisor',
    description: 'Financial Advisors provide personalized financial planning and investment advice to individuals and families, helping clients achieve their financial goals through wealth management strategies.',
    alternativeTitles: ['Wealth Advisor', 'Financial Consultant', 'Investment Advisor', 'Financial Planner'],
    dailyTasks: [
      { task: 'Meet with clients to discuss financial goals', frequency: 'daily', timePercentage: 25 },
      { task: 'Develop personalized financial plans', frequency: 'daily', timePercentage: 20 },
      { task: 'Research and recommend investment products', frequency: 'daily', timePercentage: 15 },
      { task: 'Monitor client portfolios and market conditions', frequency: 'daily', timePercentage: 15 },
      { task: 'Prospect for new clients and networking', frequency: 'daily', timePercentage: 10 },
      { task: 'Review and rebalance investment portfolios', frequency: 'weekly', timePercentage: 10 },
      { task: 'Stay updated on financial regulations and products', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Financial planning', category: 'technical', importance: 'required', description: 'Comprehensive financial planning expertise' },
      { skill: 'Investment analysis', category: 'technical', importance: 'required' },
      { skill: 'Portfolio management', category: 'technical', importance: 'required' },
      { skill: 'Tax planning knowledge', category: 'technical', importance: 'required' },
      { skill: 'Retirement planning', category: 'technical', importance: 'required' },
      { skill: 'Estate planning basics', category: 'technical', importance: 'preferred' },
      { skill: 'Insurance products', category: 'technical', importance: 'preferred' },
      { skill: 'Financial software (eMoney, MoneyGuidePro)', category: 'technical', importance: 'preferred' },
      { skill: 'Relationship building', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Trustworthiness', category: 'soft', importance: 'required' },
      { skill: 'Sales skills', category: 'soft', importance: 'required' },
      { skill: 'Empathy', category: 'soft', importance: 'required' },
      { skill: 'CFP (Certified Financial Planner)', category: 'certification', importance: 'preferred' },
      { skill: 'Series 7 and 66', category: 'certification', importance: 'required' },
    ],
    salaryRanges: [
      { min: 45000, max: 65000, median: 55000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 65000, max: 95000, median: 80000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 95000, max: 150000, median: 122500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Junior Financial Advisor / Associate Advisor',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 45000, max: 65000, median: 55000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Client support', 'Research', 'Portfolio monitoring', 'Learning products'],
        requiredSkills: ['Series 7/66', 'Financial basics', 'Client service', 'Communication'],
      },
      {
        level: 'mid',
        title: 'Financial Advisor',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 65000, max: 95000, median: 80000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Client relationships', 'Financial planning', 'Portfolio management', 'Client acquisition'],
        requiredSkills: ['CFP progress', 'Planning expertise', 'Sales ability', 'Relationship management'],
      },
      {
        level: 'senior',
        title: 'Senior Financial Advisor / Wealth Manager',
        yearsExperience: '5-10 years',
        typicalSalaryRange: { min: 95000, max: 150000, median: 122500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['High-net-worth clients', 'Complex planning', 'Team leadership', 'Practice growth'],
        requiredSkills: ['CFP certification', 'Advanced planning', 'Business development', 'Leadership'],
      },
      {
        level: 'executive',
        title: 'Managing Director / Partner',
        yearsExperience: '10+ years',
        typicalSalaryRange: { min: 150000, max: 300000, median: 225000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Firm leadership', 'Major client relationships', 'Business strategy', 'Team management'],
        requiredSkills: ['Executive leadership', 'Business ownership', 'Strategic planning', 'Extensive network'],
      },
    ],
    industryInsights: [
      {
        topic: 'Robo-advisor competition',
        description: 'Automated investment platforms driving advisors toward holistic planning',
        trend: 'stable',
      },
      {
        topic: 'Fee-based models',
        description: 'Continued shift from commission-based to fee-only compensation',
        trend: 'growing',
      },
      {
        topic: 'Technology integration',
        description: 'Financial planning software and client portals becoming essential',
        trend: 'stable',
      },
      {
        topic: 'Specialization trend',
        description: 'Growing focus on niche markets (doctors, tech workers, retirees)',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40-50 hours per week, flexible with client meetings',
    },
    jobOutlook: {
      growthRate: '15% (2021-2031, much faster than average)',
      projectedJobs: '38,400 openings per year',
      competitionLevel: 'high',
    },
    education: {
      minimumDegree: 'Bachelor of Science in Finance, Business, or related field',
      preferredDegree: 'Bachelor\'s with CFP certification',
      certifications: ['CFP (Certified Financial Planner)', 'Series 7', 'Series 66', 'CFA', 'ChFC (Chartered Financial Consultant)'],
      alternativePathways: ['Career change programs', 'Insurance agent to advisor', 'Bank branch to advisory', 'Financial planning programs'],
    },
    relatedRoles: ['Wealth Manager', 'Investment Advisor', 'Retirement Planner', 'Estate Planner', 'Financial Consultant'],
    keywords: ['financial advisor', 'wealth management', 'financial planning', 'investment advisor', 'CFP', 'retirement planning'],
  },
  {
    id: 'investment-banker',
    category: 'finance',
    title: 'Investment Banker',
    description: 'Investment Bankers provide financial advisory services to corporations and governments, facilitating mergers and acquisitions, capital raising, and other complex financial transactions.',
    alternativeTitles: ['M&A Analyst', 'Corporate Finance Analyst', 'IBD Analyst', 'Capital Markets Analyst'],
    dailyTasks: [
      { task: 'Build financial models and valuation analyses', frequency: 'daily', timePercentage: 30 },
      { task: 'Prepare pitch books and client presentations', frequency: 'daily', timePercentage: 25 },
      { task: 'Conduct industry and company research', frequency: 'daily', timePercentage: 15 },
      { task: 'Support deal execution and due diligence', frequency: 'daily', timePercentage: 15 },
      { task: 'Attend client meetings and calls', frequency: 'weekly', timePercentage: 10 },
      { task: 'Coordinate with legal and accounting teams', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Financial modeling and valuation', category: 'technical', importance: 'required', description: 'Advanced modeling expertise' },
      { skill: 'Excel (expert level)', category: 'technical', importance: 'required' },
      { skill: 'PowerPoint presentation', category: 'technical', importance: 'required' },
      { skill: 'Accounting and finance principles', category: 'technical', importance: 'required' },
      { skill: 'M&A process knowledge', category: 'technical', importance: 'required' },
      { skill: 'Capital markets understanding', category: 'technical', importance: 'preferred' },
      { skill: 'Bloomberg Terminal', category: 'technical', importance: 'preferred' },
      { skill: 'Legal document review', category: 'technical', importance: 'preferred' },
      { skill: 'Analytical thinking', category: 'soft', importance: 'required' },
      { skill: 'Attention to detail', category: 'soft', importance: 'required' },
      { skill: 'Work ethic', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Pressure management', category: 'soft', importance: 'required' },
      { skill: 'Series 79 and 63', category: 'certification', importance: 'required' },
      { skill: 'CFA', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 100000, max: 150000, median: 125000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 150000, max: 250000, median: 200000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 250000, max: 400000, median: 325000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Analyst',
        yearsExperience: '0-3 years',
        typicalSalaryRange: { min: 100000, max: 150000, median: 125000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Financial modeling', 'Pitch book creation', 'Research', 'Data analysis'],
        requiredSkills: ['Excel mastery', 'Financial modeling', 'PowerPoint', 'Long hours capability'],
      },
      {
        level: 'mid',
        title: 'Associate',
        yearsExperience: '3-6 years',
        typicalSalaryRange: { min: 150000, max: 250000, median: 200000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Deal execution', 'Client interaction', 'Team management', 'Quality control'],
        requiredSkills: ['Advanced modeling', 'Deal experience', 'Leadership', 'Client management'],
      },
      {
        level: 'senior',
        title: 'Vice President',
        yearsExperience: '6-10 years',
        typicalSalaryRange: { min: 250000, max: 400000, median: 325000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Deal leadership', 'Client relationships', 'Junior banker development', 'Transaction strategy'],
        requiredSkills: ['Deal leadership', 'Relationship management', 'Strategic thinking', 'Mentoring'],
      },
      {
        level: 'executive',
        title: 'Managing Director',
        yearsExperience: '10+ years',
        typicalSalaryRange: { min: 400000, max: 1000000, median: 700000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Client origination', 'Team leadership', 'Major deals', 'Firm strategy'],
        requiredSkills: ['Business development', 'Executive relationships', 'Strategic leadership', 'Extensive network'],
      },
    ],
    industryInsights: [
      {
        topic: 'Increased deal activity',
        description: 'Strong M&A market with private equity and strategic transactions',
        trend: 'growing',
      },
      {
        topic: 'Technology disruption',
        description: 'Fintech and automation changing traditional banking processes',
        trend: 'stable',
      },
      {
        topic: 'Work-life balance focus',
        description: 'Banks implementing policies to address analyst burnout',
        trend: 'growing',
      },
      {
        topic: 'Sector specialization',
        description: 'Growing emphasis on industry expertise and vertical specialization',
        trend: 'stable',
      },
    ],
    workEnvironment: {
      remote: false,
      hybrid: true,
      onsite: true,
      travelRequired: true,
      typicalHours: '70-100 hours per week, especially at junior levels',
    },
    jobOutlook: {
      growthRate: '7% (2021-2031, as fast as average)',
      projectedJobs: '50,200 openings per year for securities, commodities, and financial services',
      competitionLevel: 'high',
    },
    education: {
      minimumDegree: 'Bachelor of Science in Finance, Economics, or Business from target school',
      preferredDegree: 'Top-tier university (Ivy League or equivalent) or MBA',
      certifications: ['Series 79 and 63', 'CFA (Chartered Financial Analyst)', 'MBA from top program'],
      alternativePathways: ['Big 4 Transaction Advisory to IB', 'Corporate development to IB', 'MBA recruiting', 'Boutique bank to bulge bracket'],
    },
    relatedRoles: ['Private Equity Analyst', 'Corporate Development', 'Equity Research Analyst', 'Venture Capital Analyst'],
    keywords: ['investment banking', 'M&A', 'mergers and acquisitions', 'financial modeling', 'IBD', 'capital markets', 'valuation'],
  },
  {
    id: 'controller',
    category: 'finance',
    title: 'Controller',
    description: 'Controllers oversee all accounting operations, manage financial reporting, ensure regulatory compliance, and provide strategic financial leadership to organizations.',
    alternativeTitles: ['Comptroller', 'Chief Accounting Officer', 'Director of Accounting', 'Financial Controller'],
    dailyTasks: [
      { task: 'Oversee accounting department operations', frequency: 'daily', timePercentage: 25 },
      { task: 'Review and approve financial statements', frequency: 'daily', timePercentage: 20 },
      { task: 'Manage month-end and year-end close processes', frequency: 'daily', timePercentage: 15 },
      { task: 'Ensure compliance with accounting standards and regulations', frequency: 'daily', timePercentage: 15 },
      { task: 'Meet with executive team and stakeholders', frequency: 'daily', timePercentage: 10 },
      { task: 'Coordinate external audits', frequency: 'weekly', timePercentage: 10 },
      { task: 'Develop and implement financial controls', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'GAAP and IFRS expertise', category: 'technical', importance: 'required', description: 'Accounting standards mastery' },
      { skill: 'Financial reporting', category: 'technical', importance: 'required' },
      { skill: 'Internal controls', category: 'technical', importance: 'required' },
      { skill: 'ERP systems (SAP, Oracle, NetSuite)', category: 'technical', importance: 'required' },
      { skill: 'Audit management', category: 'technical', importance: 'required' },
      { skill: 'Team management', category: 'technical', importance: 'required' },
      { skill: 'Budgeting and forecasting', category: 'technical', importance: 'preferred' },
      { skill: 'SOX compliance', category: 'technical', importance: 'preferred' },
      { skill: 'Leadership', category: 'soft', importance: 'required' },
      { skill: 'Strategic thinking', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Problem-solving', category: 'soft', importance: 'required' },
      { skill: 'Decision-making', category: 'soft', importance: 'required' },
      { skill: 'CPA (Certified Public Accountant)', category: 'certification', importance: 'required' },
      { skill: 'CMA (Certified Management Accountant)', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 90000, max: 120000, median: 105000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 120000, max: 160000, median: 140000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 160000, max: 220000, median: 190000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Assistant Controller',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 90000, max: 120000, median: 105000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Support controller', 'Supervise accounting staff', 'Financial reporting', 'Process oversight'],
        requiredSkills: ['CPA', 'Accounting expertise', 'Team leadership', 'Financial reporting'],
      },
      {
        level: 'mid',
        title: 'Controller',
        yearsExperience: '8-12 years',
        typicalSalaryRange: { min: 120000, max: 160000, median: 140000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Accounting leadership', 'Financial statements', 'Audit management', 'Strategic planning'],
        requiredSkills: ['CPA', 'Leadership', 'GAAP mastery', 'Strategic thinking'],
      },
      {
        level: 'senior',
        title: 'Senior Controller / VP of Accounting',
        yearsExperience: '12-15 years',
        typicalSalaryRange: { min: 160000, max: 220000, median: 190000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Large organization oversight', 'Multi-entity reporting', 'Executive collaboration', 'Department strategy'],
        requiredSkills: ['CPA', 'Executive leadership', 'Complex accounting', 'Business acumen'],
      },
      {
        level: 'executive',
        title: 'CFO (Chief Financial Officer)',
        yearsExperience: '15+ years',
        typicalSalaryRange: { min: 220000, max: 400000, median: 310000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Financial strategy', 'C-suite leadership', 'Board reporting', 'Company strategy'],
        requiredSkills: ['Executive leadership', 'Strategic vision', 'Capital allocation', 'Board relations'],
      },
    ],
    industryInsights: [
      {
        topic: 'Digital transformation',
        description: 'Cloud ERP systems and automation transforming controller role',
        trend: 'growing',
      },
      {
        topic: 'Real-time reporting',
        description: 'Shift toward continuous accounting and faster close processes',
        trend: 'growing',
      },
      {
        topic: 'Strategic partnership',
        description: 'Controllers becoming strategic business partners, not just reporting',
        trend: 'stable',
      },
      {
        topic: 'ESG reporting',
        description: 'Growing responsibility for environmental and social governance reporting',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: false,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '50-60 hours per week, especially during close and audit periods',
    },
    jobOutlook: {
      growthRate: '6% (2021-2031, as fast as average)',
      projectedJobs: '136,400 openings per year for accountants and auditors',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: 'Bachelor of Science in Accounting',
      preferredDegree: 'Bachelor\'s with CPA and MBA',
      certifications: ['CPA (Certified Public Accountant)', 'CMA (Certified Management Accountant)', 'MBA'],
      alternativePathways: ['Big 4 to corporate controller', 'Senior Accountant to Assistant Controller', 'Industry accounting progression'],
    },
    relatedRoles: ['CFO', 'Director of Finance', 'VP of Finance', 'Chief Accounting Officer', 'Assistant Controller'],
    keywords: ['controller', 'comptroller', 'accounting manager', 'financial reporting', 'CPA', 'GAAP', 'audit'],
  },
];