import { JobCategory } from '@/types/career';

export const healthcareRoles: JobCategory[] = [
  {
    id: 'registered-nurse',
    category: 'healthcare',
    title: 'Registered Nurse (RN)',
    description: 'Registered Nurses provide and coordinate patient care, educate patients about health conditions, and provide advice and emotional support to patients and their families.',
    alternativeTitles: ['RN', 'Staff Nurse', 'Clinical Nurse', 'Bedside Nurse'],
    dailyTasks: [
      { task: 'Assess patient conditions and monitor vital signs', frequency: 'daily', timePercentage: 25 },
      { task: 'Administer medications and treatments', frequency: 'daily', timePercentage: 20 },
      { task: 'Document patient care and update medical records', frequency: 'daily', timePercentage: 15 },
      { task: 'Collaborate with physicians and healthcare team', frequency: 'daily', timePercentage: 15 },
      { task: 'Educate patients and families about care plans', frequency: 'daily', timePercentage: 10 },
      { task: 'Operate and monitor medical equipment', frequency: 'daily', timePercentage: 10 },
      { task: 'Respond to emergencies and provide critical care', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Patient care', category: 'technical', importance: 'required', description: 'Ability to provide comprehensive patient care' },
      { skill: 'Clinical assessment', category: 'technical', importance: 'required' },
      { skill: 'Medication administration', category: 'technical', importance: 'required' },
      { skill: 'IV therapy', category: 'technical', importance: 'required' },
      { skill: 'EMR/EHR systems', category: 'technical', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Critical thinking', category: 'soft', importance: 'required' },
      { skill: 'Empathy', category: 'soft', importance: 'required' },
      { skill: 'Time management', category: 'soft', importance: 'required' },
      { skill: 'BLS certification', category: 'certification', importance: 'required' },
      { skill: 'ACLS certification', category: 'certification', importance: 'preferred' },
      { skill: 'Specialty certification (e.g., CCRN)', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 60000, max: 75000, median: 67500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 70000, max: 90000, median: 80000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 85000, max: 110000, median: 97500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'New Graduate RN',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 60000, max: 75000, median: 67500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Basic patient care', 'Following care protocols', 'Learning clinical skills', 'Documentation'],
        requiredSkills: ['RN license', 'BLS certification', 'Basic clinical skills'],
      },
      {
        level: 'mid',
        title: 'Experienced RN',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 70000, max: 90000, median: 80000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Independent patient care', 'Mentoring new nurses', 'Complex care management', 'Quality improvement'],
        requiredSkills: ['Advanced clinical skills', 'ACLS certification', 'Specialty knowledge'],
      },
      {
        level: 'senior',
        title: 'Charge Nurse / Clinical Nurse Specialist',
        yearsExperience: '5+ years',
        typicalSalaryRange: { min: 85000, max: 110000, median: 97500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Unit leadership', 'Staff scheduling', 'Policy development', 'Complex case management'],
        requiredSkills: ['Leadership', 'Advanced certifications', 'Specialized expertise'],
      },
      {
        level: 'executive',
        title: 'Nurse Manager / Director of Nursing',
        yearsExperience: '10+ years',
        typicalSalaryRange: { min: 100000, max: 150000, median: 125000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Department management', 'Budget oversight', 'Strategic planning', 'Quality assurance'],
        requiredSkills: ['Leadership', 'Business management', 'MSN degree'],
      },
    ],
    industryInsights: [
      {
        topic: 'Nursing shortage',
        description: 'Ongoing nationwide shortage creating high demand and competitive salaries',
        trend: 'growing',
      },
      {
        topic: 'Travel nursing',
        description: 'Significant growth in travel nursing opportunities with premium pay',
        trend: 'growing',
      },
      {
        topic: 'Telehealth nursing',
        description: 'Expanding role of nurses in remote patient monitoring and virtual care',
        trend: 'growing',
      },
      {
        topic: 'Work-life balance',
        description: 'Increasing focus on nurse burnout prevention and flexible scheduling',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: false,
      hybrid: false,
      onsite: true,
      travelRequired: false,
      typicalHours: '3x12-hour shifts per week (varies by facility)',
    },
    jobOutlook: {
      growthRate: '6% (2021-2031, faster than average)',
      projectedJobs: '195,400 openings per year',
      competitionLevel: 'low',
    },
    education: {
      minimumDegree: 'Associate Degree in Nursing (ADN)',
      preferredDegree: 'Bachelor of Science in Nursing (BSN)',
      certifications: ['RN License (NCLEX-RN)', 'BLS', 'ACLS'],
      alternativePathways: ['Diploma programs', 'Accelerated BSN for career changers', 'Military nursing programs'],
    },
    relatedRoles: ['Licensed Practical Nurse', 'Nurse Practitioner', 'Clinical Nurse Specialist', 'Nurse Educator'],
    keywords: ['nursing', 'patient care', 'healthcare', 'RN', 'clinical', 'medical', 'hospital'],
  },
  {
    id: 'medical-assistant',
    category: 'healthcare',
    title: 'Medical Assistant',
    description: 'Medical Assistants perform administrative and clinical tasks to support physicians and other healthcare professionals in medical offices and clinics.',
    alternativeTitles: ['MA', 'Clinical Medical Assistant', 'Certified Medical Assistant', 'CMA'],
    dailyTasks: [
      { task: 'Room patients and take vital signs', frequency: 'daily', timePercentage: 20 },
      { task: 'Prepare patients for examination', frequency: 'daily', timePercentage: 15 },
      { task: 'Assist physicians during exams', frequency: 'daily', timePercentage: 15 },
      { task: 'Document patient information in EHR', frequency: 'daily', timePercentage: 15 },
      { task: 'Schedule appointments and manage calls', frequency: 'daily', timePercentage: 10 },
      { task: 'Perform basic lab tests', frequency: 'daily', timePercentage: 10 },
      { task: 'Give injections and medications', frequency: 'daily', timePercentage: 10 },
      { task: 'Sterilize equipment and maintain exam rooms', frequency: 'daily', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Vital signs measurement', category: 'technical', importance: 'required' },
      { skill: 'EHR systems', category: 'technical', importance: 'required' },
      { skill: 'Phlebotomy', category: 'technical', importance: 'preferred' },
      { skill: 'Patient scheduling', category: 'technical', importance: 'required' },
      { skill: 'Medical terminology', category: 'technical', importance: 'required' },
      { skill: 'Customer service', category: 'soft', importance: 'required' },
      { skill: 'Multitasking', category: 'soft', importance: 'required' },
      { skill: 'Attention to detail', category: 'soft', importance: 'required' },
      { skill: 'CMA certification', category: 'certification', importance: 'preferred' },
      { skill: 'BLS certification', category: 'certification', importance: 'preferred' },
    ],
    salaryRanges: [
      { min: 32000, max: 40000, median: 36000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 38000, max: 48000, median: 43000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 45000, max: 55000, median: 50000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Medical Assistant',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 32000, max: 40000, median: 36000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Basic patient care', 'Vital signs', 'Scheduling', 'Documentation'],
        requiredSkills: ['Medical terminology', 'EHR systems', 'Customer service'],
      },
      {
        level: 'mid',
        title: 'Certified Medical Assistant',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 38000, max: 48000, median: 43000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Advanced procedures', 'Training new staff', 'Inventory management'],
        requiredSkills: ['CMA certification', 'Phlebotomy', 'Lab procedures'],
      },
      {
        level: 'senior',
        title: 'Lead Medical Assistant / Office Manager',
        yearsExperience: '5+ years',
        typicalSalaryRange: { min: 45000, max: 55000, median: 50000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Staff supervision', 'Workflow optimization', 'Quality assurance'],
        requiredSkills: ['Leadership', 'Office management', 'Advanced certifications'],
      },
    ],
    industryInsights: [
      {
        topic: 'High demand',
        description: 'Medical assistants are one of the fastest-growing occupations',
        trend: 'growing',
      },
      {
        topic: 'Outpatient care growth',
        description: 'Shift to outpatient facilities increasing MA opportunities',
        trend: 'growing',
      },
      {
        topic: 'Scope expansion',
        description: 'MAs taking on more clinical responsibilities in some states',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: false,
      hybrid: false,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, some evenings/weekends',
    },
    jobOutlook: {
      growthRate: '16% (2021-2031, much faster than average)',
      projectedJobs: '104,400 openings per year',
      competitionLevel: 'low',
    },
    education: {
      minimumDegree: 'High school diploma or equivalent',
      preferredDegree: 'Certificate from accredited MA program',
      certifications: ['CMA (Certified Medical Assistant)', 'RMA (Registered Medical Assistant)', 'BLS'],
      alternativePathways: ['On-the-job training', 'Community college programs', 'Online certification programs'],
    },
    relatedRoles: ['Phlebotomist', 'Patient Care Technician', 'LPN', 'Medical Receptionist'],
    keywords: ['medical assistant', 'MA', 'clinic', 'patient care', 'healthcare', 'clinical support'],
  },
];