import { JobCategory } from '@/types/career';

export const marketingRoles: JobCategory[] = [
  {
    id: 'digital-marketing-manager',
    category: 'marketing',
    title: 'Digital Marketing Manager',
    description: 'Digital Marketing Managers develop and execute online marketing strategies across multiple channels to drive brand awareness, customer acquisition, and revenue growth.',
    alternativeTitles: ['Digital Marketing Lead', 'Online Marketing Manager', 'Growth Marketing Manager', 'Performance Marketing Manager'],
    dailyTasks: [
      { task: 'Plan and execute digital marketing campaigns', frequency: 'daily', timePercentage: 25 },
      { task: 'Analyze campaign performance and metrics', frequency: 'daily', timePercentage: 20 },
      { task: 'Manage marketing budgets and ROI', frequency: 'daily', timePercentage: 15 },
      { task: 'Coordinate with content, design, and sales teams', frequency: 'daily', timePercentage: 15 },
      { task: 'Optimize paid advertising campaigns', frequency: 'daily', timePercentage: 10 },
      { task: 'Report on marketing performance to stakeholders', frequency: 'weekly', timePercentage: 10 },
      { task: 'Research market trends and competitors', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Google Ads and Facebook Ads', category: 'technical', importance: 'required', description: 'Paid advertising platform expertise' },
      { skill: 'Google Analytics', category: 'technical', importance: 'required' },
      { skill: 'Marketing automation (HubSpot, Marketo)', category: 'technical', importance: 'required' },
      { skill: 'Email marketing platforms', category: 'technical', importance: 'required' },
      { skill: 'SEO/SEM knowledge', category: 'technical', importance: 'required' },
      { skill: 'A/B testing', category: 'technical', importance: 'preferred' },
      { skill: 'CRM systems (Salesforce)', category: 'technical', importance: 'preferred' },
      { skill: 'Data visualization (Tableau, Looker)', category: 'technical', importance: 'preferred' },
      { skill: 'Strategic thinking', category: 'soft', importance: 'required' },
      { skill: 'Analytical skills', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Project management', category: 'soft', importance: 'required' },
      { skill: 'Creativity', category: 'soft', importance: 'required' },
      { skill: 'Google Analytics Certification', category: 'certification', importance: 'preferred' },
      { skill: 'HubSpot Marketing Certification', category: 'certification', importance: 'nice-to-have' },
      { skill: 'Facebook Blueprint Certification', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 55000, max: 70000, median: 62500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 70000, max: 95000, median: 82500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 95000, max: 130000, median: 112500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Digital Marketing Coordinator',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 55000, max: 70000, median: 62500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Campaign execution', 'Social media posting', 'Basic analytics', 'Content scheduling'],
        requiredSkills: ['Social media platforms', 'Basic analytics', 'Content creation', 'Organization'],
      },
      {
        level: 'mid',
        title: 'Digital Marketing Manager',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 70000, max: 95000, median: 82500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Campaign strategy', 'Budget management', 'Team coordination', 'Performance optimization'],
        requiredSkills: ['Paid advertising', 'Marketing automation', 'Data analysis', 'Strategy development'],
      },
      {
        level: 'senior',
        title: 'Senior Digital Marketing Manager',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 95000, max: 130000, median: 112500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Marketing strategy', 'Multi-channel campaigns', 'Team leadership', 'Revenue attribution'],
        requiredSkills: ['Strategic leadership', 'Advanced analytics', 'Budget planning', 'Cross-functional leadership'],
      },
      {
        level: 'executive',
        title: 'Director of Digital Marketing',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 130000, max: 180000, median: 155000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Marketing vision', 'Department leadership', 'Strategic planning', 'Executive reporting'],
        requiredSkills: ['Executive leadership', 'Strategic vision', 'P&L management', 'Stakeholder management'],
      },
    ],
    industryInsights: [
      {
        topic: 'AI in marketing',
        description: 'Growing use of AI for personalization, content generation, and predictive analytics',
        trend: 'growing',
      },
      {
        topic: 'Privacy changes',
        description: 'Adapting to cookie deprecation and privacy regulations affecting targeting',
        trend: 'stable',
      },
      {
        topic: 'Multi-touch attribution',
        description: 'Increased focus on understanding full customer journey and attribution modeling',
        trend: 'growing',
      },
      {
        topic: 'Video content dominance',
        description: 'Short-form video and streaming platforms becoming primary channels',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, occasional evening/weekend campaigns',
    },
    jobOutlook: {
      growthRate: '10% (2021-2031, faster than average)',
      projectedJobs: '31,100 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: 'Bachelor of Arts in Marketing, Business, or Communications',
      preferredDegree: 'Bachelor\'s with marketing certifications or MBA',
      certifications: ['Google Analytics', 'Google Ads', 'HubSpot Marketing', 'Facebook Blueprint', 'Hootsuite Social Marketing'],
      alternativePathways: ['Digital marketing bootcamps', 'Self-taught with portfolio', 'Internal company transitions', 'Online certification programs'],
    },
    relatedRoles: ['Content Marketing Manager', 'Growth Manager', 'Performance Marketing Manager', 'Marketing Analyst'],
    keywords: ['digital marketing', 'online marketing', 'PPC', 'SEM', 'campaigns', 'analytics', 'ROI', 'advertising'],
  },
  {
    id: 'content-marketing-specialist',
    category: 'marketing',
    title: 'Content Marketing Specialist',
    description: 'Content Marketing Specialists create and distribute valuable, relevant content to attract and engage target audiences, building brand authority and driving customer action.',
    alternativeTitles: ['Content Strategist', 'Content Writer', 'Content Creator', 'Content Manager'],
    dailyTasks: [
      { task: 'Create blog posts, articles, and web content', frequency: 'daily', timePercentage: 30 },
      { task: 'Develop content strategy and editorial calendar', frequency: 'daily', timePercentage: 15 },
      { task: 'Research industry trends and keywords', frequency: 'daily', timePercentage: 15 },
      { task: 'Optimize content for SEO', frequency: 'daily', timePercentage: 15 },
      { task: 'Collaborate with design and marketing teams', frequency: 'daily', timePercentage: 10 },
      { task: 'Analyze content performance metrics', frequency: 'daily', timePercentage: 10 },
      { task: 'Edit and proofread content', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Content writing and copywriting', category: 'technical', importance: 'required', description: 'Excellent writing skills' },
      { skill: 'SEO best practices', category: 'technical', importance: 'required' },
      { skill: 'Content management systems (WordPress)', category: 'technical', importance: 'required' },
      { skill: 'Google Analytics', category: 'technical', importance: 'required' },
      { skill: 'Keyword research tools', category: 'technical', importance: 'preferred' },
      { skill: 'Social media platforms', category: 'technical', importance: 'preferred' },
      { skill: 'Basic HTML/CSS', category: 'technical', importance: 'nice-to-have' },
      { skill: 'Video editing basics', category: 'technical', importance: 'nice-to-have' },
      { skill: 'Creativity', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Attention to detail', category: 'soft', importance: 'required' },
      { skill: 'Time management', category: 'soft', importance: 'required' },
      { skill: 'Adaptability', category: 'soft', importance: 'required' },
      { skill: 'HubSpot Content Marketing', category: 'certification', importance: 'nice-to-have' },
      { skill: 'Content Marketing Institute Certification', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 45000, max: 60000, median: 52500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 60000, max: 80000, median: 70000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 80000, max: 110000, median: 95000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Junior Content Writer',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 45000, max: 60000, median: 52500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Write blog posts', 'Basic SEO', 'Content editing', 'Social media support'],
        requiredSkills: ['Writing skills', 'Basic SEO', 'CMS platforms', 'Grammar'],
      },
      {
        level: 'mid',
        title: 'Content Marketing Specialist',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 60000, max: 80000, median: 70000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Content strategy', 'Editorial calendar', 'Performance analysis', 'Multi-format content'],
        requiredSkills: ['Advanced SEO', 'Content strategy', 'Analytics', 'Multiple content formats'],
      },
      {
        level: 'senior',
        title: 'Senior Content Strategist',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 80000, max: 110000, median: 95000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Content strategy leadership', 'Team management', 'Brand voice', 'Cross-channel campaigns'],
        requiredSkills: ['Strategic planning', 'Leadership', 'Brand development', 'Data-driven decisions'],
      },
      {
        level: 'executive',
        title: 'Director of Content Marketing',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 110000, max: 150000, median: 130000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Content vision', 'Team leadership', 'Strategic planning', 'Budget management'],
        requiredSkills: ['Executive leadership', 'Strategic vision', 'Team building', 'Business acumen'],
      },
    ],
    industryInsights: [
      {
        topic: 'AI content tools',
        description: 'ChatGPT and AI writing assistants transforming content creation workflows',
        trend: 'growing',
      },
      {
        topic: 'Video content growth',
        description: 'Shift towards short-form video, podcasts, and multimedia content',
        trend: 'growing',
      },
      {
        topic: 'User-generated content',
        description: 'Increased focus on community-driven and authentic content',
        trend: 'growing',
      },
      {
        topic: 'Quality over quantity',
        description: 'Emphasis on high-quality, valuable content rather than volume',
        trend: 'stable',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, flexible schedules common',
    },
    jobOutlook: {
      growthRate: '10% (2021-2031, faster than average)',
      projectedJobs: '15,400 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: 'Bachelor of Arts in English, Marketing, Communications, or Journalism',
      preferredDegree: 'Bachelor\'s with portfolio and certifications',
      certifications: ['HubSpot Content Marketing', 'Google Analytics', 'Content Marketing Institute', 'Copyblogger Certified Content Marketer'],
      alternativePathways: ['Freelance writing portfolio', 'Journalism background', 'Content bootcamps', 'Self-taught with published work'],
    },
    relatedRoles: ['Content Writer', 'Copywriter', 'SEO Specialist', 'Social Media Manager', 'Brand Journalist'],
    keywords: ['content marketing', 'content writing', 'copywriting', 'SEO', 'blog', 'editorial', 'content strategy'],
  },
  {
    id: 'social-media-manager',
    category: 'marketing',
    title: 'Social Media Manager',
    description: 'Social Media Managers develop and implement social media strategies, create engaging content, manage online communities, and analyze performance across social platforms.',
    alternativeTitles: ['Social Media Strategist', 'Community Manager', 'Social Media Coordinator', 'Social Content Manager'],
    dailyTasks: [
      { task: 'Create and schedule social media content', frequency: 'daily', timePercentage: 25 },
      { task: 'Monitor and respond to comments and messages', frequency: 'daily', timePercentage: 20 },
      { task: 'Analyze social media metrics and engagement', frequency: 'daily', timePercentage: 15 },
      { task: 'Develop social media campaigns', frequency: 'daily', timePercentage: 15 },
      { task: 'Collaborate with content and design teams', frequency: 'daily', timePercentage: 10 },
      { task: 'Stay updated on social media trends', frequency: 'daily', timePercentage: 10 },
      { task: 'Report on social media performance', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Social media platforms (Instagram, Facebook, Twitter, LinkedIn, TikTok)', category: 'technical', importance: 'required', description: 'Platform expertise' },
      { skill: 'Social media management tools (Hootsuite, Buffer, Sprout Social)', category: 'technical', importance: 'required' },
      { skill: 'Content creation and copywriting', category: 'technical', importance: 'required' },
      { skill: 'Basic graphic design (Canva, Adobe Creative Suite)', category: 'technical', importance: 'preferred' },
      { skill: 'Social media analytics', category: 'technical', importance: 'required' },
      { skill: 'Paid social advertising', category: 'technical', importance: 'preferred' },
      { skill: 'Video editing basics', category: 'technical', importance: 'preferred' },
      { skill: 'Community management', category: 'technical', importance: 'required' },
      { skill: 'Creativity', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Responsiveness', category: 'soft', importance: 'required' },
      { skill: 'Strategic thinking', category: 'soft', importance: 'required' },
      { skill: 'Adaptability', category: 'soft', importance: 'required' },
      { skill: 'Hootsuite Social Marketing Certification', category: 'certification', importance: 'nice-to-have' },
      { skill: 'Facebook Blueprint Certification', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 42000, max: 55000, median: 48500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 55000, max: 75000, median: 65000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 75000, max: 100000, median: 87500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Social Media Coordinator',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 42000, max: 55000, median: 48500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Content posting', 'Community engagement', 'Basic analytics', 'Scheduling'],
        requiredSkills: ['Social platforms', 'Content creation', 'Scheduling tools', 'Communication'],
      },
      {
        level: 'mid',
        title: 'Social Media Manager',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 55000, max: 75000, median: 65000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Strategy development', 'Campaign management', 'Analytics reporting', 'Team coordination'],
        requiredSkills: ['Platform strategy', 'Paid advertising', 'Analytics', 'Content planning'],
      },
      {
        level: 'senior',
        title: 'Senior Social Media Manager',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 75000, max: 100000, median: 87500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Social strategy leadership', 'Multi-platform campaigns', 'Team management', 'Crisis management'],
        requiredSkills: ['Strategic leadership', 'Advanced analytics', 'Team leadership', 'Crisis communication'],
      },
      {
        level: 'executive',
        title: 'Director of Social Media',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 100000, max: 140000, median: 120000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Social media vision', 'Department leadership', 'Brand strategy', 'Executive reporting'],
        requiredSkills: ['Executive leadership', 'Strategic planning', 'Brand management', 'Influencer relations'],
      },
    ],
    industryInsights: [
      {
        topic: 'Short-form video dominance',
        description: 'TikTok, Reels, and Shorts driving content strategy across platforms',
        trend: 'growing',
      },
      {
        topic: 'Social commerce growth',
        description: 'Direct shopping features integrated into social platforms',
        trend: 'growing',
      },
      {
        topic: 'Authenticity focus',
        description: 'Move away from polished content toward authentic, relatable posts',
        trend: 'growing',
      },
      {
        topic: 'AI content tools',
        description: 'AI assistants helping with caption writing and content ideation',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, some evening/weekend monitoring',
    },
    jobOutlook: {
      growthRate: '10% (2021-2031, faster than average)',
      projectedJobs: '31,100 openings per year',
      competitionLevel: 'high',
    },
    education: {
      minimumDegree: 'Bachelor of Arts in Marketing, Communications, or related field',
      preferredDegree: 'Bachelor\'s with social media certifications and portfolio',
      certifications: ['Hootsuite Social Marketing', 'Facebook Blueprint', 'Twitter Flight School', 'HubSpot Social Media'],
      alternativePathways: ['Self-taught with portfolio', 'Personal brand building', 'Internships', 'Freelance social media management'],
    },
    relatedRoles: ['Community Manager', 'Content Creator', 'Influencer Marketing Manager', 'Digital Marketing Manager'],
    keywords: ['social media', 'social media marketing', 'community management', 'Instagram', 'TikTok', 'content creation'],
  },
  {
    id: 'seo-specialist',
    category: 'marketing',
    title: 'SEO Specialist',
    description: 'SEO Specialists optimize websites and content to improve search engine rankings, increase organic traffic, and enhance online visibility through technical and content strategies.',
    alternativeTitles: ['SEO Analyst', 'SEO Manager', 'Search Engine Optimization Specialist', 'Organic Search Specialist'],
    dailyTasks: [
      { task: 'Conduct keyword research and analysis', frequency: 'daily', timePercentage: 20 },
      { task: 'Optimize website content and metadata', frequency: 'daily', timePercentage: 20 },
      { task: 'Analyze website performance and rankings', frequency: 'daily', timePercentage: 15 },
      { task: 'Perform technical SEO audits', frequency: 'daily', timePercentage: 15 },
      { task: 'Build and monitor backlink strategies', frequency: 'daily', timePercentage: 10 },
      { task: 'Collaborate with content and development teams', frequency: 'daily', timePercentage: 10 },
      { task: 'Report on SEO metrics and recommendations', frequency: 'weekly', timePercentage: 10 },
    ],
    requiredSkills: [
      { skill: 'SEO tools (Ahrefs, SEMrush, Moz)', category: 'technical', importance: 'required', description: 'SEO platform expertise' },
      { skill: 'Google Search Console and Analytics', category: 'technical', importance: 'required' },
      { skill: 'Keyword research', category: 'technical', importance: 'required' },
      { skill: 'On-page and off-page SEO', category: 'technical', importance: 'required' },
      { skill: 'Technical SEO', category: 'technical', importance: 'required' },
      { skill: 'HTML/CSS basics', category: 'technical', importance: 'preferred' },
      { skill: 'Content management systems', category: 'technical', importance: 'preferred' },
      { skill: 'Link building strategies', category: 'technical', importance: 'preferred' },
      { skill: 'Schema markup', category: 'technical', importance: 'nice-to-have' },
      { skill: 'Analytical thinking', category: 'soft', importance: 'required' },
      { skill: 'Attention to detail', category: 'soft', importance: 'required' },
      { skill: 'Problem-solving', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Patience', category: 'soft', importance: 'required' },
      { skill: 'Google Analytics Certification', category: 'certification', importance: 'preferred' },
      { skill: 'SEMrush SEO Toolkit Certification', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 48000, max: 62000, median: 55000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 62000, max: 85000, median: 73500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 85000, max: 115000, median: 100000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Junior SEO Specialist',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 48000, max: 62000, median: 55000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Keyword research', 'Content optimization', 'Basic audits', 'Reporting'],
        requiredSkills: ['SEO basics', 'Analytics tools', 'Keyword research', 'Content optimization'],
      },
      {
        level: 'mid',
        title: 'SEO Specialist',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 62000, max: 85000, median: 73500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Technical SEO', 'Link building', 'Strategy development', 'Performance optimization'],
        requiredSkills: ['Technical SEO', 'Link strategies', 'Analytics', 'Strategic planning'],
      },
      {
        level: 'senior',
        title: 'Senior SEO Manager',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 85000, max: 115000, median: 100000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['SEO strategy leadership', 'Team management', 'Enterprise SEO', 'Cross-channel integration'],
        requiredSkills: ['Strategic leadership', 'Advanced technical SEO', 'Team management', 'Enterprise experience'],
      },
      {
        level: 'executive',
        title: 'Director of SEO',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 115000, max: 160000, median: 137500, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['SEO vision', 'Department leadership', 'Strategic planning', 'Executive reporting'],
        requiredSkills: ['Executive leadership', 'Strategic vision', 'Business acumen', 'Team building'],
      },
    ],
    industryInsights: [
      {
        topic: 'AI search evolution',
        description: 'Google SGE and AI-powered search changing optimization strategies',
        trend: 'growing',
      },
      {
        topic: 'Core Web Vitals',
        description: 'Page experience and technical performance increasingly important for rankings',
        trend: 'stable',
      },
      {
        topic: 'E-E-A-T emphasis',
        description: 'Experience, Expertise, Authoritativeness, and Trust critical for content',
        trend: 'growing',
      },
      {
        topic: 'Video SEO growth',
        description: 'YouTube and video content optimization becoming essential',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, flexible schedules common',
    },
    jobOutlook: {
      growthRate: '8% (2021-2031, as fast as average)',
      projectedJobs: '22,900 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: 'Bachelor of Arts in Marketing, Communications, or related field',
      preferredDegree: 'Bachelor\'s with SEO certifications and proven track record',
      certifications: ['Google Analytics', 'Google Search Console', 'SEMrush SEO Toolkit', 'Moz SEO Certification', 'HubSpot SEO'],
      alternativePathways: ['Self-taught with portfolio', 'Digital marketing bootcamps', 'Freelance SEO work', 'Content writing to SEO transition'],
    },
    relatedRoles: ['SEM Specialist', 'Content Marketing Specialist', 'Digital Marketing Manager', 'Web Analyst'],
    keywords: ['SEO', 'search engine optimization', 'organic search', 'keyword research', 'rankings', 'google', 'backlinks'],
  },
  {
    id: 'marketing-analyst',
    category: 'marketing',
    title: 'Marketing Analyst',
    description: 'Marketing Analysts collect, analyze, and interpret marketing data to provide insights that drive strategic decisions, optimize campaigns, and measure ROI across marketing channels.',
    alternativeTitles: ['Digital Marketing Analyst', 'Marketing Data Analyst', 'Marketing Intelligence Analyst', 'Performance Analyst'],
    dailyTasks: [
      { task: 'Analyze marketing campaign performance', frequency: 'daily', timePercentage: 25 },
      { task: 'Create reports and dashboards', frequency: 'daily', timePercentage: 20 },
      { task: 'Conduct market research and competitive analysis', frequency: 'daily', timePercentage: 15 },
      { task: 'Track KPIs and marketing metrics', frequency: 'daily', timePercentage: 15 },
      { task: 'Collaborate with marketing teams on insights', frequency: 'daily', timePercentage: 10 },
      { task: 'Perform A/B testing analysis', frequency: 'daily', timePercentage: 10 },
      { task: 'Present findings to stakeholders', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Google Analytics and marketing analytics', category: 'technical', importance: 'required', description: 'Analytics platform expertise' },
      { skill: 'Excel and data analysis', category: 'technical', importance: 'required' },
      { skill: 'SQL', category: 'technical', importance: 'preferred' },
      { skill: 'Data visualization (Tableau, Looker, Power BI)', category: 'technical', importance: 'preferred' },
      { skill: 'Statistical analysis', category: 'technical', importance: 'preferred' },
      { skill: 'A/B testing methodologies', category: 'technical', importance: 'preferred' },
      { skill: 'CRM platforms (Salesforce)', category: 'technical', importance: 'nice-to-have' },
      { skill: 'Python or R', category: 'technical', importance: 'nice-to-have' },
      { skill: 'Analytical thinking', category: 'soft', importance: 'required' },
      { skill: 'Attention to detail', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Problem-solving', category: 'soft', importance: 'required' },
      { skill: 'Business acumen', category: 'soft', importance: 'required' },
      { skill: 'Google Analytics Certification', category: 'certification', importance: 'preferred' },
      { skill: 'Tableau Desktop Specialist', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 52000, max: 67000, median: 59500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 67000, max: 90000, median: 78500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 90000, max: 120000, median: 105000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Junior Marketing Analyst',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 52000, max: 67000, median: 59500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Data collection', 'Basic reporting', 'Campaign tracking', 'Dashboard maintenance'],
        requiredSkills: ['Excel', 'Google Analytics', 'Basic statistics', 'Reporting'],
      },
      {
        level: 'mid',
        title: 'Marketing Analyst',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 67000, max: 90000, median: 78500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Advanced analysis', 'Insight generation', 'A/B testing', 'Strategic recommendations'],
        requiredSkills: ['Advanced analytics', 'SQL', 'Data visualization', 'Statistical analysis'],
      },
      {
        level: 'senior',
        title: 'Senior Marketing Analyst',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 90000, max: 120000, median: 105000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Strategic analytics', 'Team leadership', 'Predictive modeling', 'Executive reporting'],
        requiredSkills: ['Advanced modeling', 'Leadership', 'Strategic thinking', 'Business intelligence'],
      },
      {
        level: 'executive',
        title: 'Director of Marketing Analytics',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 120000, max: 170000, median: 145000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Analytics strategy', 'Team leadership', 'Data infrastructure', 'Executive insights'],
        requiredSkills: ['Strategic leadership', 'Executive communication', 'Team building', 'Data strategy'],
      },
    ],
    industryInsights: [
      {
        topic: 'Marketing mix modeling',
        description: 'Growing need for multi-touch attribution and holistic campaign measurement',
        trend: 'growing',
      },
      {
        topic: 'Predictive analytics',
        description: 'Increased use of machine learning for forecasting and optimization',
        trend: 'growing',
      },
      {
        topic: 'Privacy-first analytics',
        description: 'Adapting measurement strategies to privacy regulations and cookie changes',
        trend: 'growing',
      },
      {
        topic: 'Real-time insights',
        description: 'Demand for faster, automated reporting and real-time dashboards',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, flexible schedules common',
    },
    jobOutlook: {
      growthRate: '23% (2021-2031, much faster than average)',
      projectedJobs: '96,000 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: 'Bachelor of Science in Marketing, Statistics, Business Analytics, or related field',
      preferredDegree: 'Bachelor\'s with analytics certifications or Master\'s degree',
      certifications: ['Google Analytics', 'Tableau Desktop Specialist', 'Microsoft Power BI', 'HubSpot Marketing Analytics'],
      alternativePathways: ['Data analytics bootcamps', 'Self-taught with portfolio', 'Business analyst to marketing analyst', 'Internal company transitions'],
    },
    relatedRoles: ['Data Analyst', 'Business Intelligence Analyst', 'Web Analyst', 'Marketing Data Scientist'],
    keywords: ['marketing analyst', 'marketing analytics', 'data analysis', 'metrics', 'reporting', 'KPIs', 'insights'],
  },
  {
    id: 'brand-marketing-manager',
    category: 'marketing',
    title: 'Brand Marketing Manager',
    description: 'Brand Marketing Managers develop and execute strategies to build brand awareness, strengthen brand positioning, and create consistent brand experiences across all customer touchpoints.',
    alternativeTitles: ['Brand Manager', 'Brand Strategy Manager', 'Brand Development Manager', 'Product Marketing Manager'],
    dailyTasks: [
      { task: 'Develop and execute brand strategy initiatives', frequency: 'daily', timePercentage: 25 },
      { task: 'Manage brand guidelines and ensure consistency', frequency: 'daily', timePercentage: 20 },
      { task: 'Collaborate with creative teams on brand campaigns', frequency: 'daily', timePercentage: 15 },
      { task: 'Monitor brand perception and competitive positioning', frequency: 'daily', timePercentage: 15 },
      { task: 'Coordinate with product and sales teams', frequency: 'daily', timePercentage: 10 },
      { task: 'Analyze brand performance metrics', frequency: 'daily', timePercentage: 10 },
      { task: 'Present brand strategies to leadership', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Brand strategy development', category: 'technical', importance: 'required', description: 'Strategic brand planning expertise' },
      { skill: 'Market research and consumer insights', category: 'technical', importance: 'required' },
      { skill: 'Creative brief development', category: 'technical', importance: 'required' },
      { skill: 'Brand positioning frameworks', category: 'technical', importance: 'required' },
      { skill: 'Marketing analytics', category: 'technical', importance: 'preferred' },
      { skill: 'Budget management', category: 'technical', importance: 'preferred' },
      { skill: 'Campaign management platforms', category: 'technical', importance: 'preferred' },
      { skill: 'Adobe Creative Suite basics', category: 'technical', importance: 'nice-to-have' },
      { skill: 'Project management tools', category: 'technical', importance: 'nice-to-have' },
      { skill: 'Strategic thinking', category: 'soft', importance: 'required' },
      { skill: 'Creative vision', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Leadership', category: 'soft', importance: 'required' },
      { skill: 'Collaboration', category: 'soft', importance: 'required' },
      { skill: 'Brand Management Certification', category: 'certification', importance: 'nice-to-have' },
      { skill: 'AMA Professional Certified Marketer', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 58000, max: 75000, median: 66500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 75000, max: 100000, median: 87500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 100000, max: 140000, median: 120000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
      { min: 140000, max: 200000, median: 170000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Associate Brand Manager',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 58000, max: 75000, median: 66500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Brand campaign support', 'Market research assistance', 'Brand guideline compliance', 'Competitive analysis'],
        requiredSkills: ['Marketing fundamentals', 'Research skills', 'Communication', 'Brand awareness'],
      },
      {
        level: 'mid',
        title: 'Brand Marketing Manager',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 75000, max: 100000, median: 87500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Brand strategy development', 'Campaign leadership', 'Cross-functional collaboration', 'Brand performance tracking'],
        requiredSkills: ['Brand strategy', 'Campaign management', 'Analytics', 'Creative direction'],
      },
      {
        level: 'senior',
        title: 'Senior Brand Manager',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 100000, max: 140000, median: 120000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Brand portfolio management', 'Strategic positioning', 'Team leadership', 'Brand architecture'],
        requiredSkills: ['Strategic leadership', 'Portfolio management', 'P&L responsibility', 'Executive presentation'],
      },
      {
        level: 'executive',
        title: 'VP of Brand Marketing',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 140000, max: 200000, median: 170000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Brand vision and strategy', 'Department leadership', 'Corporate positioning', 'Executive stakeholder management'],
        requiredSkills: ['Executive leadership', 'Strategic vision', 'Business strategy', 'Organizational influence'],
      },
    ],
    industryInsights: [
      {
        topic: 'Purpose-driven branding',
        description: 'Increasing emphasis on brand values, sustainability, and social responsibility',
        trend: 'growing',
      },
      {
        topic: 'Brand experience focus',
        description: 'Shift from brand messaging to creating holistic brand experiences',
        trend: 'growing',
      },
      {
        topic: 'Personal brand integration',
        description: 'CEO and employee personal brands becoming part of corporate brand strategy',
        trend: 'growing',
      },
      {
        topic: 'AI-powered personalization',
        description: 'Using AI to deliver personalized brand experiences at scale',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: true,
      typicalHours: '40-45 hours per week, occasional events and launches',
    },
    jobOutlook: {
      growthRate: '10% (2021-2031, faster than average)',
      projectedJobs: '28,600 openings per year',
      competitionLevel: 'high',
    },
    education: {
      minimumDegree: 'Bachelor of Arts in Marketing, Business, Communications, or related field',
      preferredDegree: 'Bachelor\'s with brand management experience or MBA',
      certifications: ['AMA Professional Certified Marketer', 'Brand Management Certification', 'Product Marketing Alliance Certification', 'Google Analytics'],
      alternativePathways: ['Product management to brand', 'Agency brand strategy experience', 'Internal marketing rotations', 'Consumer packaged goods experience'],
    },
    relatedRoles: ['Product Marketing Manager', 'Marketing Manager', 'Creative Director', 'Brand Strategist'],
    keywords: ['brand marketing', 'brand management', 'brand strategy', 'positioning', 'brand awareness', 'brand identity', 'brand campaigns'],
  },
  {
    id: 'digital-marketing-coordinator',
    category: 'marketing',
    title: 'Digital Marketing Coordinator',
    description: 'Digital Marketing Coordinators support digital marketing initiatives by executing campaigns, managing schedules, coordinating with teams, and tracking performance across digital channels.',
    alternativeTitles: ['Marketing Coordinator', 'Digital Marketing Associate', 'Marketing Assistant', 'Campaign Coordinator'],
    dailyTasks: [
      { task: 'Schedule and coordinate digital marketing campaigns', frequency: 'daily', timePercentage: 25 },
      { task: 'Manage social media content calendar and posting', frequency: 'daily', timePercentage: 20 },
      { task: 'Track campaign metrics and compile reports', frequency: 'daily', timePercentage: 15 },
      { task: 'Coordinate with designers and content creators', frequency: 'daily', timePercentage: 15 },
      { task: 'Update website content and landing pages', frequency: 'daily', timePercentage: 10 },
      { task: 'Assist with email marketing campaigns', frequency: 'daily', timePercentage: 10 },
      { task: 'Administrative support for marketing team', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Social media platforms', category: 'technical', importance: 'required', description: 'Platform familiarity and posting' },
      { skill: 'Email marketing tools (Mailchimp, Constant Contact)', category: 'technical', importance: 'required' },
      { skill: 'Content management systems (WordPress)', category: 'technical', importance: 'required' },
      { skill: 'Google Analytics basics', category: 'technical', importance: 'preferred' },
      { skill: 'Microsoft Office Suite', category: 'technical', importance: 'required' },
      { skill: 'Project management tools (Asana, Trello)', category: 'technical', importance: 'preferred' },
      { skill: 'Basic graphic design (Canva)', category: 'technical', importance: 'preferred' },
      { skill: 'Scheduling tools (Hootsuite, Buffer)', category: 'technical', importance: 'preferred' },
      { skill: 'Organization', category: 'soft', importance: 'required' },
      { skill: 'Attention to detail', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Time management', category: 'soft', importance: 'required' },
      { skill: 'Adaptability', category: 'soft', importance: 'required' },
      { skill: 'HubSpot Marketing Software Certification', category: 'certification', importance: 'nice-to-have' },
      { skill: 'Google Analytics Certification', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 40000, max: 52000, median: 46000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 52000, max: 65000, median: 58500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 65000, max: 80000, median: 72500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
      { min: 80000, max: 100000, median: 90000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Digital Marketing Coordinator',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 40000, max: 52000, median: 46000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Campaign execution', 'Social media scheduling', 'Basic reporting', 'Administrative support'],
        requiredSkills: ['Social media', 'Organization', 'Basic analytics', 'Communication'],
      },
      {
        level: 'mid',
        title: 'Digital Marketing Specialist',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 52000, max: 65000, median: 58500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Campaign management', 'Strategy support', 'Performance optimization', 'Team coordination'],
        requiredSkills: ['Campaign management', 'Analytics', 'Strategy development', 'Marketing tools'],
      },
      {
        level: 'senior',
        title: 'Digital Marketing Manager',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 65000, max: 80000, median: 72500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Strategy development', 'Team leadership', 'Budget management', 'Cross-channel campaigns'],
        requiredSkills: ['Strategic planning', 'Leadership', 'Budget management', 'Advanced analytics'],
      },
      {
        level: 'executive',
        title: 'Senior Digital Marketing Manager',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 80000, max: 100000, median: 90000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Marketing strategy', 'Department management', 'Revenue attribution', 'Executive reporting'],
        requiredSkills: ['Executive leadership', 'Strategic vision', 'P&L responsibility', 'Stakeholder management'],
      },
    ],
    industryInsights: [
      {
        topic: 'Marketing automation growth',
        description: 'Increasing adoption of automation tools for campaign execution and nurturing',
        trend: 'growing',
      },
      {
        topic: 'Cross-channel coordination',
        description: 'Greater need for coordinated campaigns across multiple digital channels',
        trend: 'stable',
      },
      {
        topic: 'Content calendar complexity',
        description: 'Managing more platforms and content types requires advanced organization',
        trend: 'growing',
      },
      {
        topic: 'Data-driven coordination',
        description: 'Using performance data to optimize campaign timing and execution',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, occasional deadline-driven overtime',
    },
    jobOutlook: {
      growthRate: '10% (2021-2031, faster than average)',
      projectedJobs: '31,100 openings per year',
      competitionLevel: 'low',
    },
    education: {
      minimumDegree: 'Bachelor of Arts in Marketing, Communications, Business, or related field',
      preferredDegree: 'Bachelor\'s with marketing internships or certifications',
      certifications: ['HubSpot Marketing Software', 'Google Analytics', 'Hootsuite Social Marketing', 'Mailchimp Email Marketing'],
      alternativePathways: ['Marketing internships', 'Associate degrees with experience', 'Self-taught with portfolio', 'Career switchers with transferable skills'],
    },
    relatedRoles: ['Marketing Assistant', 'Social Media Coordinator', 'Content Coordinator', 'Campaign Coordinator'],
    keywords: ['digital marketing', 'marketing coordinator', 'campaign coordination', 'social media scheduling', 'marketing support', 'content management'],
  },
];