import { JobCategory } from '@/types/career';

export const techRoles: JobCategory[] = [
  {
    id: 'software-engineer-frontend',
    category: 'tech',
    title: 'Frontend Software Engineer',
    description: 'Frontend Software Engineers design and build user-facing web applications, focusing on creating responsive, accessible, and performant interfaces that provide excellent user experiences.',
    alternativeTitles: ['Frontend Developer', 'Front End Engineer', 'UI Engineer', 'Web Developer'],
    dailyTasks: [
      { task: 'Write and review code for web applications', frequency: 'daily', timePercentage: 35 },
      { task: 'Collaborate with designers and backend engineers', frequency: 'daily', timePercentage: 15 },
      { task: 'Debug and optimize application performance', frequency: 'daily', timePercentage: 15 },
      { task: 'Participate in code reviews and team meetings', frequency: 'daily', timePercentage: 10 },
      { task: 'Implement responsive and accessible UI components', frequency: 'daily', timePercentage: 10 },
      { task: 'Write unit and integration tests', frequency: 'daily', timePercentage: 10 },
      { task: 'Update documentation and technical specifications', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'JavaScript/TypeScript', category: 'technical', importance: 'required', description: 'Proficiency in modern JavaScript and TypeScript' },
      { skill: 'React, Vue, or Angular', category: 'technical', importance: 'required' },
      { skill: 'HTML/CSS', category: 'technical', importance: 'required' },
      { skill: 'Git version control', category: 'technical', importance: 'required' },
      { skill: 'RESTful APIs', category: 'technical', importance: 'required' },
      { skill: 'Responsive design', category: 'technical', importance: 'required' },
      { skill: 'Build tools (Webpack, Vite)', category: 'technical', importance: 'preferred' },
      { skill: 'State management (Redux, Zustand)', category: 'technical', importance: 'preferred' },
      { skill: 'Testing frameworks (Jest, Cypress)', category: 'technical', importance: 'preferred' },
      { skill: 'Problem-solving', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Attention to detail', category: 'soft', importance: 'required' },
      { skill: 'Collaboration', category: 'soft', importance: 'required' },
      { skill: 'AWS Certified Developer', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 75000, max: 95000, median: 85000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 95000, max: 130000, median: 112500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 130000, max: 180000, median: 155000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Junior Frontend Engineer',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 75000, max: 95000, median: 85000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Build UI components', 'Fix bugs', 'Learn best practices', 'Code reviews'],
        requiredSkills: ['JavaScript/TypeScript', 'React or Vue', 'CSS', 'Git'],
      },
      {
        level: 'mid',
        title: 'Frontend Engineer',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 95000, max: 130000, median: 112500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Own feature development', 'Mentor juniors', 'Architecture decisions', 'Performance optimization'],
        requiredSkills: ['Advanced JavaScript', 'Multiple frameworks', 'Testing', 'Performance tuning'],
      },
      {
        level: 'senior',
        title: 'Senior Frontend Engineer',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 130000, max: 180000, median: 155000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Technical leadership', 'System design', 'Cross-team collaboration', 'Code quality standards'],
        requiredSkills: ['Architecture expertise', 'Leadership', 'Advanced optimization', 'Mentoring'],
      },
      {
        level: 'executive',
        title: 'Staff/Principal Engineer or Engineering Manager',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 180000, max: 250000, median: 215000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Strategic planning', 'Team leadership', 'Technical vision', 'Product strategy'],
        requiredSkills: ['Executive leadership', 'Business acumen', 'Strategic thinking', 'Cross-functional collaboration'],
      },
    ],
    industryInsights: [
      {
        topic: 'AI-assisted development',
        description: 'Growing adoption of AI coding assistants like GitHub Copilot and cursor',
        trend: 'growing',
      },
      {
        topic: 'Framework consolidation',
        description: 'React continues to dominate, with Next.js and Remix gaining significant traction',
        trend: 'stable',
      },
      {
        topic: 'TypeScript adoption',
        description: 'TypeScript becoming the standard for large-scale applications',
        trend: 'growing',
      },
      {
        topic: 'Performance focus',
        description: 'Increased emphasis on web vitals, accessibility, and user experience metrics',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, flexible schedules common',
    },
    jobOutlook: {
      growthRate: '25% (2021-2031, much faster than average)',
      projectedJobs: '162,900 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: 'Associate degree or equivalent experience',
      preferredDegree: 'Bachelor of Science in Computer Science or related field',
      certifications: ['AWS Certified Developer', 'Meta Frontend Developer Certificate', 'Google UX Design Certificate'],
      alternativePathways: ['Coding bootcamps', 'Self-taught with portfolio', 'Online certifications', 'Open source contributions'],
    },
    relatedRoles: ['Full Stack Engineer', 'UI/UX Engineer', 'Web Developer', 'Mobile Developer'],
    keywords: ['frontend', 'react', 'javascript', 'typescript', 'web development', 'UI', 'CSS', 'HTML'],
  },
  {
    id: 'software-engineer-backend',
    category: 'tech',
    title: 'Backend Software Engineer',
    description: 'Backend Software Engineers build and maintain server-side applications, databases, and APIs that power web and mobile applications, focusing on scalability, security, and performance.',
    alternativeTitles: ['Backend Developer', 'Server-Side Engineer', 'API Engineer', 'Backend Architect'],
    dailyTasks: [
      { task: 'Design and implement APIs and microservices', frequency: 'daily', timePercentage: 30 },
      { task: 'Write and optimize database queries', frequency: 'daily', timePercentage: 15 },
      { task: 'Debug and resolve production issues', frequency: 'daily', timePercentage: 15 },
      { task: 'Code reviews and technical discussions', frequency: 'daily', timePercentage: 15 },
      { task: 'Monitor system performance and scalability', frequency: 'daily', timePercentage: 10 },
      { task: 'Write tests and improve code quality', frequency: 'daily', timePercentage: 10 },
      { task: 'Documentation and architecture planning', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Python, Java, Go, or Node.js', category: 'technical', importance: 'required', description: 'Proficiency in backend programming languages' },
      { skill: 'Database design (SQL/NoSQL)', category: 'technical', importance: 'required' },
      { skill: 'RESTful API design', category: 'technical', importance: 'required' },
      { skill: 'Git version control', category: 'technical', importance: 'required' },
      { skill: 'Linux/Unix systems', category: 'technical', importance: 'required' },
      { skill: 'Cloud platforms (AWS, GCP, Azure)', category: 'technical', importance: 'preferred' },
      { skill: 'Docker and containerization', category: 'technical', importance: 'preferred' },
      { skill: 'Message queues (RabbitMQ, Kafka)', category: 'technical', importance: 'preferred' },
      { skill: 'GraphQL', category: 'technical', importance: 'nice-to-have' },
      { skill: 'Problem-solving', category: 'soft', importance: 'required' },
      { skill: 'System thinking', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'AWS Certified Solutions Architect', category: 'certification', importance: 'nice-to-have' },
      { skill: 'Kubernetes Administrator', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 80000, max: 100000, median: 90000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 100000, max: 140000, median: 120000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 140000, max: 190000, median: 165000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Junior Backend Engineer',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 80000, max: 100000, median: 90000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Build API endpoints', 'Database operations', 'Bug fixes', 'Unit testing'],
        requiredSkills: ['Backend language', 'SQL', 'REST APIs', 'Git'],
      },
      {
        level: 'mid',
        title: 'Backend Engineer',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 100000, max: 140000, median: 120000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Design systems', 'Database optimization', 'Mentoring', 'Performance tuning'],
        requiredSkills: ['System design', 'Cloud platforms', 'Microservices', 'Caching strategies'],
      },
      {
        level: 'senior',
        title: 'Senior Backend Engineer',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 140000, max: 190000, median: 165000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Architecture decisions', 'Technical leadership', 'Scalability planning', 'Cross-team projects'],
        requiredSkills: ['Distributed systems', 'Leadership', 'Architecture patterns', 'Advanced optimization'],
      },
      {
        level: 'executive',
        title: 'Staff/Principal Engineer or Engineering Manager',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 190000, max: 270000, median: 230000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Strategic architecture', 'Team leadership', 'Company-wide initiatives', 'Technology roadmap'],
        requiredSkills: ['Executive leadership', 'Strategic planning', 'Business alignment', 'Technical vision'],
      },
    ],
    industryInsights: [
      {
        topic: 'Microservices architecture',
        description: 'Continued shift from monoliths to microservices and event-driven architectures',
        trend: 'growing',
      },
      {
        topic: 'Serverless adoption',
        description: 'Growing use of serverless computing and Function-as-a-Service platforms',
        trend: 'growing',
      },
      {
        topic: 'AI integration',
        description: 'Backend systems increasingly incorporating AI/ML models and vector databases',
        trend: 'growing',
      },
      {
        topic: 'Observability',
        description: 'Greater emphasis on monitoring, logging, and distributed tracing',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, on-call rotation common',
    },
    jobOutlook: {
      growthRate: '25% (2021-2031, much faster than average)',
      projectedJobs: '162,900 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: 'Associate degree or equivalent experience',
      preferredDegree: 'Bachelor of Science in Computer Science or related field',
      certifications: ['AWS Solutions Architect', 'Google Cloud Professional', 'MongoDB Developer', 'Oracle Database Certification'],
      alternativePathways: ['Coding bootcamps', 'Self-taught with portfolio', 'Open source contributions', 'Online certifications'],
    },
    relatedRoles: ['Full Stack Engineer', 'DevOps Engineer', 'Database Administrator', 'Site Reliability Engineer'],
    keywords: ['backend', 'API', 'server', 'database', 'microservices', 'cloud', 'python', 'java', 'node'],
  },
  {
    id: 'full-stack-engineer',
    category: 'tech',
    title: 'Full Stack Software Engineer',
    description: 'Full Stack Engineers work across the entire application stack, building both client-facing interfaces and server-side systems, providing end-to-end development capabilities.',
    alternativeTitles: ['Full Stack Developer', 'Full Stack Web Developer', 'Software Engineer'],
    dailyTasks: [
      { task: 'Develop frontend and backend features', frequency: 'daily', timePercentage: 30 },
      { task: 'Design and implement database schemas', frequency: 'daily', timePercentage: 15 },
      { task: 'Build and integrate APIs', frequency: 'daily', timePercentage: 15 },
      { task: 'Debug across the full stack', frequency: 'daily', timePercentage: 15 },
      { task: 'Collaborate with product and design teams', frequency: 'daily', timePercentage: 10 },
      { task: 'Write tests and documentation', frequency: 'daily', timePercentage: 10 },
      { task: 'Deploy and monitor applications', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'JavaScript/TypeScript', category: 'technical', importance: 'required', description: 'Full stack language proficiency' },
      { skill: 'Frontend framework (React, Vue, Angular)', category: 'technical', importance: 'required' },
      { skill: 'Backend framework (Node.js, Django, Rails)', category: 'technical', importance: 'required' },
      { skill: 'Database management (SQL and NoSQL)', category: 'technical', importance: 'required' },
      { skill: 'RESTful API design', category: 'technical', importance: 'required' },
      { skill: 'Git version control', category: 'technical', importance: 'required' },
      { skill: 'Cloud services (AWS, GCP, Azure)', category: 'technical', importance: 'preferred' },
      { skill: 'Docker/Kubernetes', category: 'technical', importance: 'preferred' },
      { skill: 'CI/CD pipelines', category: 'technical', importance: 'preferred' },
      { skill: 'Problem-solving', category: 'soft', importance: 'required' },
      { skill: 'Adaptability', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Time management', category: 'soft', importance: 'required' },
    ],
    salaryRanges: [
      { min: 80000, max: 100000, median: 90000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 100000, max: 135000, median: 117500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 135000, max: 185000, median: 160000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Junior Full Stack Engineer',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 80000, max: 100000, median: 90000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Feature implementation', 'Bug fixes', 'Learning best practices', 'Code reviews'],
        requiredSkills: ['Frontend basics', 'Backend basics', 'Database fundamentals', 'Git'],
      },
      {
        level: 'mid',
        title: 'Full Stack Engineer',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 100000, max: 135000, median: 117500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['End-to-end feature ownership', 'System design', 'Mentoring', 'Architecture decisions'],
        requiredSkills: ['Advanced full stack', 'Cloud platforms', 'Performance optimization', 'Security best practices'],
      },
      {
        level: 'senior',
        title: 'Senior Full Stack Engineer',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 135000, max: 185000, median: 160000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Technical leadership', 'Complex system design', 'Cross-team collaboration', 'Strategic planning'],
        requiredSkills: ['Expert full stack', 'Architecture expertise', 'Leadership', 'Product thinking'],
      },
      {
        level: 'executive',
        title: 'Staff Engineer or Engineering Manager',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 185000, max: 260000, median: 222500, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Engineering strategy', 'Team leadership', 'Technology decisions', 'Business alignment'],
        requiredSkills: ['Strategic thinking', 'Executive leadership', 'Business acumen', 'Vision setting'],
      },
    ],
    industryInsights: [
      {
        topic: 'High demand for full stack',
        description: 'Strong demand from startups and mid-size companies valuing versatility',
        trend: 'growing',
      },
      {
        topic: 'Modern stack evolution',
        description: 'Next.js, Prisma, and tRPC creating integrated full stack experiences',
        trend: 'growing',
      },
      {
        topic: 'JAMstack architecture',
        description: 'Static site generation and serverless APIs gaining popularity',
        trend: 'stable',
      },
      {
        topic: 'DevOps integration',
        description: 'Full stack engineers increasingly expected to handle deployment and infrastructure',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, flexible schedules common',
    },
    jobOutlook: {
      growthRate: '25% (2021-2031, much faster than average)',
      projectedJobs: '162,900 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: 'Associate degree or equivalent experience',
      preferredDegree: 'Bachelor of Science in Computer Science or related field',
      certifications: ['AWS Certified Developer', 'Full Stack Web Development certifications', 'MongoDB Developer'],
      alternativePathways: ['Coding bootcamps', 'Self-taught with portfolio', 'Online courses', 'Open source work'],
    },
    relatedRoles: ['Frontend Engineer', 'Backend Engineer', 'Software Engineer', 'DevOps Engineer'],
    keywords: ['full stack', 'full-stack', 'web development', 'javascript', 'node', 'react', 'API', 'database'],
  },
  {
    id: 'data-scientist',
    category: 'tech',
    title: 'Data Scientist',
    description: 'Data Scientists analyze complex data sets, build predictive models, and extract insights to drive business decisions using statistical analysis, machine learning, and data visualization.',
    alternativeTitles: ['Machine Learning Engineer', 'Data Analyst', 'Applied Scientist', 'Research Scientist'],
    dailyTasks: [
      { task: 'Analyze and interpret complex datasets', frequency: 'daily', timePercentage: 25 },
      { task: 'Build and train machine learning models', frequency: 'daily', timePercentage: 20 },
      { task: 'Clean and preprocess data', frequency: 'daily', timePercentage: 15 },
      { task: 'Create data visualizations and reports', frequency: 'daily', timePercentage: 15 },
      { task: 'Collaborate with stakeholders on requirements', frequency: 'daily', timePercentage: 10 },
      { task: 'Deploy models to production', frequency: 'weekly', timePercentage: 10 },
      { task: 'Research new techniques and tools', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Python or R', category: 'technical', importance: 'required', description: 'Programming for data analysis' },
      { skill: 'Machine learning frameworks (scikit-learn, TensorFlow, PyTorch)', category: 'technical', importance: 'required' },
      { skill: 'SQL and database querying', category: 'technical', importance: 'required' },
      { skill: 'Statistics and probability', category: 'technical', importance: 'required' },
      { skill: 'Data visualization (Tableau, matplotlib, seaborn)', category: 'technical', importance: 'required' },
      { skill: 'Pandas and NumPy', category: 'technical', importance: 'required' },
      { skill: 'Big data tools (Spark, Hadoop)', category: 'technical', importance: 'preferred' },
      { skill: 'Cloud platforms (AWS, GCP, Azure)', category: 'technical', importance: 'preferred' },
      { skill: 'Deep learning', category: 'technical', importance: 'preferred' },
      { skill: 'Analytical thinking', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Problem-solving', category: 'soft', importance: 'required' },
      { skill: 'Business acumen', category: 'soft', importance: 'required' },
      { skill: 'AWS Machine Learning Specialty', category: 'certification', importance: 'nice-to-have' },
      { skill: 'Google Professional Data Engineer', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 85000, max: 110000, median: 97500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 110000, max: 150000, median: 130000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 150000, max: 200000, median: 175000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Junior Data Scientist / Data Analyst',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 85000, max: 110000, median: 97500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Data cleaning', 'Basic analysis', 'Reporting', 'Supporting senior data scientists'],
        requiredSkills: ['Python/R', 'SQL', 'Statistics basics', 'Data visualization'],
      },
      {
        level: 'mid',
        title: 'Data Scientist',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 110000, max: 150000, median: 130000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Build ML models', 'End-to-end projects', 'Stakeholder communication', 'Mentoring'],
        requiredSkills: ['Advanced ML', 'Feature engineering', 'Model deployment', 'Business understanding'],
      },
      {
        level: 'senior',
        title: 'Senior Data Scientist',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 150000, max: 200000, median: 175000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Lead data initiatives', 'Complex modeling', 'Strategic guidance', 'Technical leadership'],
        requiredSkills: ['Expert ML/AI', 'Leadership', 'Product strategy', 'Advanced statistics'],
      },
      {
        level: 'executive',
        title: 'Principal Data Scientist / ML Director',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 200000, max: 300000, median: 250000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Data strategy', 'Team leadership', 'Research direction', 'Business impact'],
        requiredSkills: ['Strategic leadership', 'Research expertise', 'Executive communication', 'Vision setting'],
      },
    ],
    industryInsights: [
      {
        topic: 'Generative AI explosion',
        description: 'Massive growth in LLMs, prompt engineering, and AI application development',
        trend: 'growing',
      },
      {
        topic: 'MLOps maturity',
        description: 'Increased focus on model deployment, monitoring, and lifecycle management',
        trend: 'growing',
      },
      {
        topic: 'Real-time analytics',
        description: 'Growing demand for streaming data and real-time decision systems',
        trend: 'growing',
      },
      {
        topic: 'AutoML adoption',
        description: 'Automated machine learning tools democratizing model building',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, flexible schedules common',
    },
    jobOutlook: {
      growthRate: '36% (2021-2031, much faster than average)',
      projectedJobs: '40,500 openings per year',
      competitionLevel: 'high',
    },
    education: {
      minimumDegree: 'Bachelor of Science in Computer Science, Statistics, or related field',
      preferredDegree: 'Master\'s degree in Data Science, Machine Learning, or PhD',
      certifications: ['AWS Machine Learning Specialty', 'Google Professional Data Engineer', 'Microsoft Azure Data Scientist'],
      alternativePathways: ['Data science bootcamps', 'Online certifications (Coursera, DataCamp)', 'Self-taught with portfolio projects', 'Kaggle competitions'],
    },
    relatedRoles: ['Machine Learning Engineer', 'Data Analyst', 'Data Engineer', 'Research Scientist', 'Business Intelligence Analyst'],
    keywords: ['data science', 'machine learning', 'python', 'statistics', 'AI', 'analytics', 'modeling', 'ML'],
  },
  {
    id: 'devops-engineer',
    category: 'tech',
    title: 'DevOps Engineer',
    description: 'DevOps Engineers bridge development and operations, automating infrastructure, managing deployments, and ensuring system reliability, scalability, and security.',
    alternativeTitles: ['Site Reliability Engineer', 'Platform Engineer', 'Infrastructure Engineer', 'Cloud Engineer'],
    dailyTasks: [
      { task: 'Manage and optimize cloud infrastructure', frequency: 'daily', timePercentage: 25 },
      { task: 'Build and maintain CI/CD pipelines', frequency: 'daily', timePercentage: 20 },
      { task: 'Monitor system performance and respond to alerts', frequency: 'daily', timePercentage: 15 },
      { task: 'Automate deployment and infrastructure processes', frequency: 'daily', timePercentage: 15 },
      { task: 'Collaborate with development teams', frequency: 'daily', timePercentage: 10 },
      { task: 'Implement security and compliance measures', frequency: 'daily', timePercentage: 10 },
      { task: 'Incident response and troubleshooting', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Linux/Unix administration', category: 'technical', importance: 'required', description: 'System administration expertise' },
      { skill: 'Cloud platforms (AWS, GCP, Azure)', category: 'technical', importance: 'required' },
      { skill: 'Docker and Kubernetes', category: 'technical', importance: 'required' },
      { skill: 'CI/CD tools (Jenkins, GitLab CI, GitHub Actions)', category: 'technical', importance: 'required' },
      { skill: 'Infrastructure as Code (Terraform, CloudFormation)', category: 'technical', importance: 'required' },
      { skill: 'Scripting (Bash, Python)', category: 'technical', importance: 'required' },
      { skill: 'Monitoring tools (Prometheus, Grafana, Datadog)', category: 'technical', importance: 'preferred' },
      { skill: 'Configuration management (Ansible, Chef, Puppet)', category: 'technical', importance: 'preferred' },
      { skill: 'Git version control', category: 'technical', importance: 'required' },
      { skill: 'Problem-solving', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Adaptability', category: 'soft', importance: 'required' },
      { skill: 'Attention to detail', category: 'soft', importance: 'required' },
      { skill: 'AWS Solutions Architect', category: 'certification', importance: 'preferred' },
      { skill: 'Certified Kubernetes Administrator', category: 'certification', importance: 'preferred' },
    ],
    salaryRanges: [
      { min: 85000, max: 105000, median: 95000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 105000, max: 145000, median: 125000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 145000, max: 195000, median: 170000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Junior DevOps Engineer',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 85000, max: 105000, median: 95000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Basic infrastructure tasks', 'Pipeline maintenance', 'Monitoring', 'Documentation'],
        requiredSkills: ['Linux basics', 'Cloud fundamentals', 'CI/CD basics', 'Scripting'],
      },
      {
        level: 'mid',
        title: 'DevOps Engineer',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 105000, max: 145000, median: 125000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Infrastructure design', 'Automation', 'Performance optimization', 'Security implementation'],
        requiredSkills: ['Kubernetes', 'Terraform', 'Advanced cloud', 'System architecture'],
      },
      {
        level: 'senior',
        title: 'Senior DevOps Engineer / SRE',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 145000, max: 195000, median: 170000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Architecture decisions', 'Technical leadership', 'Scalability planning', 'Mentoring'],
        requiredSkills: ['Expert infrastructure', 'Leadership', 'Complex systems', 'Strategic planning'],
      },
      {
        level: 'executive',
        title: 'Staff SRE / Platform Engineering Manager',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 195000, max: 280000, median: 237500, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Platform strategy', 'Team leadership', 'Cross-org initiatives', 'Technology vision'],
        requiredSkills: ['Strategic leadership', 'Executive communication', 'Business alignment', 'Vision setting'],
      },
    ],
    industryInsights: [
      {
        topic: 'Platform engineering rise',
        description: 'Shift towards internal developer platforms and self-service infrastructure',
        trend: 'growing',
      },
      {
        topic: 'GitOps adoption',
        description: 'Growing use of Git as single source of truth for infrastructure and deployments',
        trend: 'growing',
      },
      {
        topic: 'FinOps emergence',
        description: 'Increased focus on cloud cost optimization and financial accountability',
        trend: 'growing',
      },
      {
        topic: 'Security shift-left',
        description: 'DevSecOps integrating security earlier in development process',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, on-call rotation required',
    },
    jobOutlook: {
      growthRate: '25% (2021-2031, much faster than average)',
      projectedJobs: '162,900 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: 'Associate degree or equivalent experience',
      preferredDegree: 'Bachelor of Science in Computer Science, IT, or related field',
      certifications: ['AWS Solutions Architect', 'Certified Kubernetes Administrator', 'HashiCorp Terraform', 'Linux+ certification'],
      alternativePathways: ['Self-taught with hands-on projects', 'Cloud certifications', 'System administration background', 'Open source contributions'],
    },
    relatedRoles: ['Site Reliability Engineer', 'Cloud Engineer', 'System Administrator', 'Platform Engineer', 'Infrastructure Engineer'],
    keywords: ['devops', 'SRE', 'cloud', 'kubernetes', 'docker', 'CI/CD', 'infrastructure', 'automation', 'AWS'],
  },
  {
    id: 'product-manager',
    category: 'tech',
    title: 'Product Manager',
    description: 'Product Managers define product vision and strategy, prioritize features, and coordinate cross-functional teams to deliver products that meet customer needs and business goals.',
    alternativeTitles: ['Technical Product Manager', 'Product Owner', 'Digital Product Manager', 'Senior Product Manager'],
    dailyTasks: [
      { task: 'Define and prioritize product roadmap', frequency: 'daily', timePercentage: 20 },
      { task: 'Conduct user research and analyze feedback', frequency: 'daily', timePercentage: 15 },
      { task: 'Collaborate with engineering and design teams', frequency: 'daily', timePercentage: 20 },
      { task: 'Write product requirements and user stories', frequency: 'daily', timePercentage: 15 },
      { task: 'Analyze metrics and product performance', frequency: 'daily', timePercentage: 10 },
      { task: 'Stakeholder meetings and presentations', frequency: 'daily', timePercentage: 10 },
      { task: 'Market research and competitive analysis', frequency: 'weekly', timePercentage: 10 },
    ],
    requiredSkills: [
      { skill: 'Product strategy', category: 'technical', importance: 'required', description: 'Ability to define product vision and roadmap' },
      { skill: 'User research methods', category: 'technical', importance: 'required' },
      { skill: 'Data analysis', category: 'technical', importance: 'required' },
      { skill: 'Agile/Scrum methodology', category: 'technical', importance: 'required' },
      { skill: 'Product analytics tools (Mixpanel, Amplitude)', category: 'technical', importance: 'preferred' },
      { skill: 'SQL basics', category: 'technical', importance: 'preferred' },
      { skill: 'Wireframing tools (Figma, Sketch)', category: 'technical', importance: 'preferred' },
      { skill: 'Technical understanding', category: 'technical', importance: 'preferred' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Strategic thinking', category: 'soft', importance: 'required' },
      { skill: 'Prioritization', category: 'soft', importance: 'required' },
      { skill: 'Leadership', category: 'soft', importance: 'required' },
      { skill: 'Empathy', category: 'soft', importance: 'required' },
      { skill: 'Certified Scrum Product Owner', category: 'certification', importance: 'nice-to-have' },
      { skill: 'Pragmatic Marketing Certification', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 85000, max: 110000, median: 97500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 110000, max: 150000, median: 130000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 150000, max: 200000, median: 175000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Associate Product Manager',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 85000, max: 110000, median: 97500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Feature documentation', 'User research support', 'Market analysis', 'Backlog management'],
        requiredSkills: ['Basic product knowledge', 'Communication', 'Data analysis', 'Agile basics'],
      },
      {
        level: 'mid',
        title: 'Product Manager',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 110000, max: 150000, median: 130000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Own product features', 'Roadmap planning', 'Cross-functional leadership', 'Launch execution'],
        requiredSkills: ['Product strategy', 'Metrics analysis', 'Stakeholder management', 'Technical depth'],
      },
      {
        level: 'senior',
        title: 'Senior Product Manager',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 150000, max: 200000, median: 175000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Product strategy', 'Multiple features/teams', 'Mentoring PMs', 'Vision setting'],
        requiredSkills: ['Strategic vision', 'Leadership', 'Business acumen', 'Advanced analytics'],
      },
      {
        level: 'executive',
        title: 'Director/VP of Product',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 200000, max: 300000, median: 250000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Product portfolio strategy', 'Team leadership', 'Company strategy', 'P&L ownership'],
        requiredSkills: ['Executive leadership', 'Business strategy', 'Team building', 'Vision setting'],
      },
    ],
    industryInsights: [
      {
        topic: 'AI product integration',
        description: 'Every PM now expected to understand AI/ML capabilities and integration',
        trend: 'growing',
      },
      {
        topic: 'Data-driven decisions',
        description: 'Increasing emphasis on quantitative analysis and experimentation',
        trend: 'stable',
      },
      {
        topic: 'Customer-centric approach',
        description: 'Greater focus on continuous discovery and user feedback loops',
        trend: 'growing',
      },
      {
        topic: 'Technical PM demand',
        description: 'Growing need for PMs with strong technical backgrounds for complex products',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40-50 hours per week, flexible schedules',
    },
    jobOutlook: {
      growthRate: '10% (2021-2031, faster than average)',
      projectedJobs: '35,000 openings per year',
      competitionLevel: 'high',
    },
    education: {
      minimumDegree: 'Bachelor of Science in Business, Computer Science, or related field',
      preferredDegree: 'MBA or Master\'s degree',
      certifications: ['Certified Scrum Product Owner', 'Pragmatic Marketing', 'Product Management certifications'],
      alternativePathways: ['Engineering to PM transition', 'Product management bootcamps', 'Internal transition from related roles', 'Startup experience'],
    },
    relatedRoles: ['Technical Product Manager', 'Product Owner', 'Program Manager', 'Product Marketing Manager'],
    keywords: ['product manager', 'product management', 'roadmap', 'agile', 'scrum', 'strategy', 'user research', 'PM'],
  },
  {
    id: 'ux-ui-designer',
    category: 'tech',
    title: 'UX/UI Designer',
    description: 'UX/UI Designers create intuitive and visually appealing digital experiences by researching user needs, designing interfaces, and ensuring products are both functional and delightful to use.',
    alternativeTitles: ['Product Designer', 'User Experience Designer', 'Interface Designer', 'Digital Designer'],
    dailyTasks: [
      { task: 'Design user interfaces and interactions', frequency: 'daily', timePercentage: 30 },
      { task: 'Conduct user research and usability testing', frequency: 'daily', timePercentage: 15 },
      { task: 'Create wireframes and prototypes', frequency: 'daily', timePercentage: 20 },
      { task: 'Collaborate with product and engineering teams', frequency: 'daily', timePercentage: 15 },
      { task: 'Iterate designs based on feedback', frequency: 'daily', timePercentage: 10 },
      { task: 'Maintain design systems and components', frequency: 'daily', timePercentage: 5 },
      { task: 'Present designs to stakeholders', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Figma or Sketch', category: 'technical', importance: 'required', description: 'Design tool proficiency' },
      { skill: 'User research methods', category: 'technical', importance: 'required' },
      { skill: 'Information architecture', category: 'technical', importance: 'required' },
      { skill: 'Interaction design', category: 'technical', importance: 'required' },
      { skill: 'Prototyping', category: 'technical', importance: 'required' },
      { skill: 'Visual design principles', category: 'technical', importance: 'required' },
      { skill: 'Design systems', category: 'technical', importance: 'preferred' },
      { skill: 'HTML/CSS basics', category: 'technical', importance: 'preferred' },
      { skill: 'Accessibility (WCAG)', category: 'technical', importance: 'preferred' },
      { skill: 'Empathy', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Collaboration', category: 'soft', importance: 'required' },
      { skill: 'Critical thinking', category: 'soft', importance: 'required' },
      { skill: 'Attention to detail', category: 'soft', importance: 'required' },
      { skill: 'Google UX Design Certificate', category: 'certification', importance: 'nice-to-have' },
      { skill: 'Nielsen Norman Group UX Certification', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 65000, max: 85000, median: 75000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 85000, max: 120000, median: 102500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 120000, max: 165000, median: 142500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Junior UX/UI Designer',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 65000, max: 85000, median: 75000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Create mockups', 'User research support', 'Design system maintenance', 'Basic prototyping'],
        requiredSkills: ['Figma/Sketch', 'Basic UX principles', 'Visual design', 'Communication'],
      },
      {
        level: 'mid',
        title: 'UX/UI Designer',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 85000, max: 120000, median: 102500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Own feature design', 'Lead user research', 'Complex prototypes', 'Cross-functional collaboration'],
        requiredSkills: ['Advanced design skills', 'User research', 'Interaction design', 'Presentation'],
      },
      {
        level: 'senior',
        title: 'Senior UX/UI Designer / Lead Designer',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 120000, max: 165000, median: 142500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Design strategy', 'Mentoring designers', 'Design system architecture', 'Stakeholder management'],
        requiredSkills: ['Design leadership', 'Strategic thinking', 'System design', 'Mentoring'],
      },
      {
        level: 'executive',
        title: 'Design Manager / Director of Design',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 165000, max: 230000, median: 197500, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Design vision', 'Team leadership', 'Product strategy', 'Organization influence'],
        requiredSkills: ['Leadership', 'Strategic vision', 'Team building', 'Business acumen'],
      },
    ],
    industryInsights: [
      {
        topic: 'AI design tools',
        description: 'AI-powered design assistants and automation transforming workflows',
        trend: 'growing',
      },
      {
        topic: 'Design systems maturity',
        description: 'Widespread adoption of comprehensive design systems in organizations',
        trend: 'stable',
      },
      {
        topic: 'Accessibility focus',
        description: 'Increased emphasis on inclusive design and WCAG compliance',
        trend: 'growing',
      },
      {
        topic: 'Product thinking',
        description: 'UX designers increasingly expected to understand business metrics and product strategy',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, flexible schedules common',
    },
    jobOutlook: {
      growthRate: '16% (2021-2031, much faster than average)',
      projectedJobs: '23,900 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: 'Associate degree or portfolio',
      preferredDegree: 'Bachelor of Arts in Design, HCI, or related field',
      certifications: ['Google UX Design Certificate', 'Nielsen Norman Group UX Certification', 'Interaction Design Foundation'],
      alternativePathways: ['Design bootcamps', 'Self-taught with portfolio', 'Online courses', 'Career transition programs'],
    },
    relatedRoles: ['Product Designer', 'Visual Designer', 'Interaction Designer', 'UX Researcher', 'UI Developer'],
    keywords: ['UX', 'UI', 'user experience', 'interface design', 'figma', 'wireframe', 'prototype', 'design'],
  },
];