import { JobCategory } from '@/types/career';

export const wellnessRoles: JobCategory[] = [
  {
    id: 'wellness-coordinator',
    category: 'wellness',
    title: 'Wellness Coordinator',
    description: 'Wellness Coordinators design, implement, and manage workplace wellness programs to improve employee health, reduce healthcare costs, and boost productivity through health education, fitness initiatives, and preventive care programs.',
    alternativeTitles: ['Employee Wellness Coordinator', 'Workplace Wellness Specialist', 'Health and Wellness Coordinator', 'Wellness Program Coordinator'],
    dailyTasks: [
      { task: 'Plan and coordinate wellness events and health screenings', frequency: 'daily', timePercentage: 20 },
      { task: 'Communicate wellness program benefits to employees', frequency: 'daily', timePercentage: 15 },
      { task: 'Track participation metrics and program outcomes', frequency: 'daily', timePercentage: 15 },
      { task: 'Develop educational materials and health resources', frequency: 'daily', timePercentage: 15 },
      { task: 'Collaborate with vendors and healthcare providers', frequency: 'daily', timePercentage: 10 },
      { task: 'Conduct individual wellness assessments', frequency: 'daily', timePercentage: 10 },
      { task: 'Manage wellness program budget and expenses', frequency: 'weekly', timePercentage: 10 },
      { task: 'Evaluate program effectiveness and prepare reports', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Program planning and management', category: 'technical', importance: 'required', description: 'Ability to design and execute wellness initiatives' },
      { skill: 'Health education', category: 'technical', importance: 'required' },
      { skill: 'Data tracking and analysis', category: 'technical', importance: 'required' },
      { skill: 'Microsoft Office Suite', category: 'technical', importance: 'required' },
      { skill: 'Wellness software platforms', category: 'technical', importance: 'preferred' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Organization', category: 'soft', importance: 'required' },
      { skill: 'Interpersonal skills', category: 'soft', importance: 'required' },
      { skill: 'Creativity', category: 'soft', importance: 'preferred' },
      { skill: 'CHES (Certified Health Education Specialist)', category: 'certification', importance: 'preferred' },
      { skill: 'CWPC (Certified Worksite Wellness Professional)', category: 'certification', importance: 'nice-to-have' },
      { skill: 'CPR/AED certification', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 42000, max: 52000, median: 47000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 50000, max: 65000, median: 57500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 62000, max: 80000, median: 71000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Wellness Coordinator',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 42000, max: 52000, median: 47000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Event coordination', 'Program assistance', 'Employee communication', 'Basic reporting'],
        requiredSkills: ['Health education', 'Event planning', 'Communication skills'],
      },
      {
        level: 'mid',
        title: 'Senior Wellness Coordinator',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 50000, max: 65000, median: 57500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Full program management', 'Vendor relationships', 'Budget management', 'Program evaluation'],
        requiredSkills: ['CHES certification', 'Program analytics', 'Vendor management'],
      },
      {
        level: 'senior',
        title: 'Wellness Program Manager',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 62000, max: 80000, median: 71000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Strategic planning', 'Multi-site coordination', 'Team leadership', 'ROI analysis'],
        requiredSkills: ['Leadership', 'Strategic planning', 'Advanced certifications'],
      },
      {
        level: 'executive',
        title: 'Director of Wellness Programs',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 75000, max: 105000, median: 90000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Enterprise wellness strategy', 'Department management', 'Executive reporting', 'C-suite collaboration'],
        requiredSkills: ['Executive leadership', 'Business strategy', 'Change management'],
      },
    ],
    industryInsights: [
      {
        topic: 'Corporate wellness investment',
        description: 'Companies increasing wellness program budgets to improve retention and reduce healthcare costs',
        trend: 'growing',
      },
      {
        topic: 'Mental health focus',
        description: 'Expanded emphasis on mental health and stress management in wellness programs',
        trend: 'growing',
      },
      {
        topic: 'Virtual wellness',
        description: 'Hybrid and remote wellness offerings becoming standard for distributed workforces',
        trend: 'growing',
      },
      {
        topic: 'Personalized wellness',
        description: 'Data-driven, individualized wellness plans replacing one-size-fits-all approaches',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: false,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, occasional evening events',
    },
    jobOutlook: {
      growthRate: '11% (2022-2032, faster than average)',
      projectedJobs: '19,200 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: "Bachelor's degree in health promotion, public health, or related field",
      preferredDegree: "Bachelor's or Master's in health education, wellness, or public health",
      certifications: ['CHES (Certified Health Education Specialist)', 'CWPC (Certified Worksite Wellness Professional)', 'CPR/AED'],
      alternativePathways: ['Exercise science degrees', 'Nutrition programs with wellness focus', 'Health coaching certifications'],
    },
    relatedRoles: ['Corporate Wellness Specialist', 'Health Promotion Specialist', 'Employee Benefits Coordinator', 'Health Coach'],
    keywords: ['wellness', 'corporate wellness', 'employee health', 'health promotion', 'workplace wellness', 'wellness programs'],
  },
  {
    id: 'corporate-wellness-specialist',
    category: 'wellness',
    title: 'Corporate Wellness Specialist',
    description: 'Corporate Wellness Specialists work directly with organizations to assess employee health needs, design comprehensive wellness strategies, implement evidence-based interventions, and measure program impact to create healthier, more productive workplaces.',
    alternativeTitles: ['Workplace Wellness Consultant', 'Employee Health Specialist', 'Wellness Program Specialist', 'Occupational Health Specialist'],
    dailyTasks: [
      { task: 'Conduct health risk assessments and biometric screenings', frequency: 'daily', timePercentage: 20 },
      { task: 'Provide one-on-one health coaching sessions', frequency: 'daily', timePercentage: 20 },
      { task: 'Design customized wellness interventions', frequency: 'daily', timePercentage: 15 },
      { task: 'Lead group fitness classes or wellness workshops', frequency: 'daily', timePercentage: 15 },
      { task: 'Analyze health data and program metrics', frequency: 'daily', timePercentage: 10 },
      { task: 'Develop wellness communication campaigns', frequency: 'weekly', timePercentage: 10 },
      { task: 'Collaborate with HR and benefits teams', frequency: 'weekly', timePercentage: 5 },
      { task: 'Stay current on wellness research and best practices', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Health coaching', category: 'technical', importance: 'required', description: 'Ability to coach individuals on behavior change' },
      { skill: 'Biometric screening', category: 'technical', importance: 'required' },
      { skill: 'Program design', category: 'technical', importance: 'required' },
      { skill: 'Data analysis', category: 'technical', importance: 'required' },
      { skill: 'Health promotion theory', category: 'technical', importance: 'required' },
      { skill: 'Motivational interviewing', category: 'soft', importance: 'required' },
      { skill: 'Active listening', category: 'soft', importance: 'required' },
      { skill: 'Empathy', category: 'soft', importance: 'required' },
      { skill: 'Presentation skills', category: 'soft', importance: 'preferred' },
      { skill: 'NBC-HWC (National Board Certified Health & Wellness Coach)', category: 'certification', importance: 'preferred' },
      { skill: 'CHES or MCHES', category: 'certification', importance: 'preferred' },
      { skill: 'ACE Health Coach', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 45000, max: 58000, median: 51500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 55000, max: 72000, median: 63500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 68000, max: 90000, median: 79000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Corporate Wellness Specialist',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 45000, max: 58000, median: 51500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Health screenings', 'Group coaching', 'Program support', 'Data collection'],
        requiredSkills: ['Health assessment', 'Basic coaching', 'Communication'],
      },
      {
        level: 'mid',
        title: 'Senior Wellness Specialist',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 55000, max: 72000, median: 63500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Advanced coaching', 'Program customization', 'Client relationship management', 'Outcome reporting'],
        requiredSkills: ['NBC-HWC certification', 'Behavior change expertise', 'Data analysis'],
      },
      {
        level: 'senior',
        title: 'Lead Wellness Specialist',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 68000, max: 90000, median: 79000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Strategic account management', 'Team mentoring', 'Program innovation', 'ROI optimization'],
        requiredSkills: ['Leadership', 'Strategic consulting', 'Advanced certifications'],
      },
      {
        level: 'executive',
        title: 'Wellness Consulting Manager',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 85000, max: 115000, median: 100000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Client portfolio management', 'Team leadership', 'Business development', 'Thought leadership'],
        requiredSkills: ['Executive consulting', 'Business development', 'Team management'],
      },
    ],
    industryInsights: [
      {
        topic: 'Health coaching demand',
        description: 'Growing demand for certified health coaches in corporate settings',
        trend: 'growing',
      },
      {
        topic: 'Chronic disease prevention',
        description: 'Focus on preventing diabetes, heart disease, and other chronic conditions',
        trend: 'growing',
      },
      {
        topic: 'Holistic wellness',
        description: 'Shift toward addressing physical, mental, financial, and social wellbeing',
        trend: 'growing',
      },
      {
        topic: 'Technology integration',
        description: 'Wearables and wellness apps becoming integral to program delivery',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: true,
      typicalHours: '40 hours per week, flexible scheduling with some early/evening appointments',
    },
    jobOutlook: {
      growthRate: '13% (2022-2032, faster than average)',
      projectedJobs: '23,400 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: "Bachelor's degree in health science, kinesiology, or related field",
      preferredDegree: "Master's in health promotion, public health, or wellness",
      certifications: ['NBC-HWC', 'CHES/MCHES', 'ACE Health Coach', 'ACSM-CEP', 'CPR/AED'],
      alternativePathways: ['Nursing background with wellness certification', 'Exercise science with health coaching', 'RD with wellness specialization'],
    },
    relatedRoles: ['Health Coach', 'Wellness Coordinator', 'Occupational Health Nurse', 'Employee Assistance Program Counselor'],
    keywords: ['corporate wellness', 'health coaching', 'workplace health', 'wellness specialist', 'employee wellbeing', 'health promotion'],
  },
  {
    id: 'fitness-program-manager',
    category: 'wellness',
    title: 'Fitness Program Manager',
    description: 'Fitness Program Managers oversee all aspects of fitness facility operations including staff management, program development, member relations, budget management, and ensuring exceptional member experiences while driving business growth and program quality.',
    alternativeTitles: ['Fitness Director', 'Health Club Manager', 'Fitness Center Manager', 'Recreation Program Manager'],
    dailyTasks: [
      { task: 'Supervise fitness staff and personal trainers', frequency: 'daily', timePercentage: 20 },
      { task: 'Develop and update fitness programs and class schedules', frequency: 'daily', timePercentage: 15 },
      { task: 'Monitor facility operations and equipment maintenance', frequency: 'daily', timePercentage: 15 },
      { task: 'Conduct member consultations and resolve concerns', frequency: 'daily', timePercentage: 15 },
      { task: 'Recruit, hire, and train fitness personnel', frequency: 'weekly', timePercentage: 10 },
      { task: 'Manage program budget and financial performance', frequency: 'weekly', timePercentage: 10 },
      { task: 'Analyze membership data and retention metrics', frequency: 'weekly', timePercentage: 10 },
      { task: 'Ensure safety compliance and risk management', frequency: 'daily', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Fitness program design', category: 'technical', importance: 'required', description: 'Ability to create diverse, effective fitness programs' },
      { skill: 'Staff management', category: 'technical', importance: 'required' },
      { skill: 'Budget management', category: 'technical', importance: 'required' },
      { skill: 'Facility operations', category: 'technical', importance: 'required' },
      { skill: 'Exercise science knowledge', category: 'technical', importance: 'required' },
      { skill: 'Leadership', category: 'soft', importance: 'required' },
      { skill: 'Customer service', category: 'soft', importance: 'required' },
      { skill: 'Problem-solving', category: 'soft', importance: 'required' },
      { skill: 'Conflict resolution', category: 'soft', importance: 'preferred' },
      { skill: 'ACSM Certified Exercise Physiologist', category: 'certification', importance: 'preferred' },
      { skill: 'NASM-CPT or ACE-CPT', category: 'certification', importance: 'preferred' },
      { skill: 'CPR/AED and First Aid', category: 'certification', importance: 'required' },
    ],
    salaryRanges: [
      { min: 40000, max: 50000, median: 45000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 48000, max: 65000, median: 56500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 60000, max: 85000, median: 72500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Assistant Fitness Manager',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 40000, max: 50000, median: 45000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Staff scheduling', 'Program coordination', 'Member services', 'Equipment oversight'],
        requiredSkills: ['Fitness certification', 'Basic management', 'Customer service'],
      },
      {
        level: 'mid',
        title: 'Fitness Program Manager',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 48000, max: 65000, median: 56500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Full program management', 'Staff supervision', 'Budget oversight', 'Program development'],
        requiredSkills: ['Advanced certifications', 'Team leadership', 'Financial management'],
      },
      {
        level: 'senior',
        title: 'Fitness Director',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 60000, max: 85000, median: 72500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Multi-facility oversight', 'Strategic planning', 'P&L management', 'Senior team leadership'],
        requiredSkills: ['Strategic leadership', 'Business acumen', 'Change management'],
      },
      {
        level: 'executive',
        title: 'Director of Fitness Operations',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 75000, max: 110000, median: 92500, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Regional/national oversight', 'Executive strategy', 'Brand development', 'Revenue optimization'],
        requiredSkills: ['Executive leadership', 'Business strategy', 'Organizational development'],
      },
    ],
    industryInsights: [
      {
        topic: 'Boutique fitness growth',
        description: 'Specialized studios and boutique concepts creating new management opportunities',
        trend: 'growing',
      },
      {
        topic: 'Technology integration',
        description: 'Fitness technology, apps, and virtual training expanding program offerings',
        trend: 'growing',
      },
      {
        topic: 'Medical fitness',
        description: 'Growth in medically-integrated fitness facilities and programs',
        trend: 'growing',
      },
      {
        topic: 'Community-based programming',
        description: 'Increased focus on social connection and community building through fitness',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: false,
      hybrid: false,
      onsite: true,
      travelRequired: false,
      typicalHours: '45-50 hours per week, early morning/evening/weekend hours common',
    },
    jobOutlook: {
      growthRate: '8% (2022-2032, faster than average)',
      projectedJobs: '31,100 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: "Bachelor's degree in exercise science, kinesiology, or related field",
      preferredDegree: "Bachelor's or Master's in exercise science, sports management, or business",
      certifications: ['ACSM-CEP or ACSM-CPT', 'NASM-CPT', 'ACE-CPT', 'CPR/AED', 'First Aid'],
      alternativePathways: ['Business degree with fitness certifications', 'Recreation management background', 'Athletic training background'],
    },
    relatedRoles: ['Personal Training Director', 'Aquatics Director', 'Group Fitness Coordinator', 'Recreation Manager'],
    keywords: ['fitness management', 'gym manager', 'fitness director', 'health club', 'fitness programs', 'recreation management'],
  },
  {
    id: 'health-coach',
    category: 'wellness',
    title: 'Health Coach',
    description: 'Health Coaches partner with individuals to help them achieve health and wellness goals through behavior change, accountability, education, and support. They work across various settings including corporate wellness, healthcare, private practice, and telehealth platforms.',
    alternativeTitles: ['Wellness Coach', 'Lifestyle Coach', 'Integrative Health Coach', 'Behavior Change Coach'],
    dailyTasks: [
      { task: 'Conduct one-on-one coaching sessions (in-person or virtual)', frequency: 'daily', timePercentage: 35 },
      { task: 'Develop personalized wellness action plans', frequency: 'daily', timePercentage: 15 },
      { task: 'Track client progress and adjust strategies', frequency: 'daily', timePercentage: 15 },
      { task: 'Provide educational resources and recommendations', frequency: 'daily', timePercentage: 10 },
      { task: 'Document coaching sessions and client notes', frequency: 'daily', timePercentage: 10 },
      { task: 'Lead group coaching sessions or workshops', frequency: 'weekly', timePercentage: 10 },
      { task: 'Network and build client relationships', frequency: 'weekly', timePercentage: 3 },
      { task: 'Continue professional development and education', frequency: 'weekly', timePercentage: 2 },
    ],
    requiredSkills: [
      { skill: 'Motivational interviewing', category: 'technical', importance: 'required', description: 'Client-centered counseling approach for behavior change' },
      { skill: 'Goal setting and action planning', category: 'technical', importance: 'required' },
      { skill: 'Health behavior change theories', category: 'technical', importance: 'required' },
      { skill: 'Nutrition knowledge', category: 'technical', importance: 'preferred' },
      { skill: 'Wellness assessment tools', category: 'technical', importance: 'preferred' },
      { skill: 'Active listening', category: 'soft', importance: 'required' },
      { skill: 'Empathy', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Patience', category: 'soft', importance: 'required' },
      { skill: 'NBC-HWC (National Board Certified)', category: 'certification', importance: 'preferred' },
      { skill: 'ACE Health Coach', category: 'certification', importance: 'preferred' },
      { skill: 'Wellcoaches Certified Health Coach', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 38000, max: 48000, median: 43000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 45000, max: 62000, median: 53500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 58000, max: 80000, median: 69000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Health Coach',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 38000, max: 48000, median: 43000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Individual coaching', 'Goal setting support', 'Basic wellness education', 'Client follow-up'],
        requiredSkills: ['Health coaching certification', 'Basic coaching techniques', 'Communication'],
      },
      {
        level: 'mid',
        title: 'Senior Health Coach',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 45000, max: 62000, median: 53500, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Advanced coaching', 'Complex client cases', 'Group facilitation', 'Program development'],
        requiredSkills: ['NBC-HWC certification', 'Behavior change expertise', 'Group facilitation'],
      },
      {
        level: 'senior',
        title: 'Lead Health Coach / Coach Manager',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 58000, max: 80000, median: 69000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Coach supervision', 'Program design', 'Quality assurance', 'Mentor coaching'],
        requiredSkills: ['Leadership', 'Mentor coaching skills', 'Program development'],
      },
      {
        level: 'executive',
        title: 'Director of Health Coaching',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 70000, max: 95000, median: 82500, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Coaching team management', 'Strategic program development', 'Quality standards', 'Business growth'],
        requiredSkills: ['Executive leadership', 'Business development', 'Strategic planning'],
      },
    ],
    industryInsights: [
      {
        topic: 'Preventive healthcare focus',
        description: 'Healthcare systems investing in coaching to reduce chronic disease costs',
        trend: 'growing',
      },
      {
        topic: 'Virtual coaching expansion',
        description: 'Telehealth and digital coaching platforms creating new opportunities',
        trend: 'growing',
      },
      {
        topic: 'Insurance coverage',
        description: 'Growing insurance reimbursement for health coaching services',
        trend: 'growing',
      },
      {
        topic: 'Specialization demand',
        description: 'Niche coaching areas (diabetes, weight loss, stress) in high demand',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, flexible scheduling with evening/weekend appointments',
    },
    jobOutlook: {
      growthRate: '13% (2022-2032, faster than average)',
      projectedJobs: '28,900 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: "Bachelor's degree in health-related field (or equivalent experience)",
      preferredDegree: "Bachelor's or Master's in health promotion, nutrition, exercise science, or psychology",
      certifications: ['NBC-HWC', 'ACE Health Coach', 'Wellcoaches', 'ACSM-CEP', 'CPR/AED'],
      alternativePathways: ['Nursing with coaching certification', 'RD with coaching specialization', 'Mental health counseling background', 'Fitness professional transition'],
    },
    relatedRoles: ['Wellness Coach', 'Nutritionist', 'Life Coach', 'Fitness Trainer', 'Corporate Wellness Specialist'],
    keywords: ['health coach', 'wellness coach', 'behavior change', 'lifestyle coaching', 'health coaching', 'integrative health'],
  },
  {
    id: 'recreational-therapist',
    category: 'wellness',
    title: 'Recreational Therapist',
    description: 'Recreational Therapists use evidence-based recreational activities, interventions, and leisure education to improve the physical, cognitive, emotional, and social functioning of individuals with illnesses, disabilities, or other conditions in clinical and community settings.',
    alternativeTitles: ['Therapeutic Recreation Specialist', 'RT', 'Recreation Therapist', 'CTRS', 'Activity Therapist'],
    dailyTasks: [
      { task: 'Assess client needs and develop treatment plans', frequency: 'daily', timePercentage: 20 },
      { task: 'Implement therapeutic recreation interventions', frequency: 'daily', timePercentage: 25 },
      { task: 'Document client progress and treatment outcomes', frequency: 'daily', timePercentage: 15 },
      { task: 'Facilitate group therapy sessions and activities', frequency: 'daily', timePercentage: 15 },
      { task: 'Collaborate with interdisciplinary treatment team', frequency: 'daily', timePercentage: 10 },
      { task: 'Educate clients and families about leisure resources', frequency: 'daily', timePercentage: 5 },
      { task: 'Plan and organize therapeutic programs and events', frequency: 'weekly', timePercentage: 5 },
      { task: 'Maintain equipment and therapy materials', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Assessment and treatment planning', category: 'technical', importance: 'required', description: 'Ability to assess client needs and develop treatment plans' },
      { skill: 'Therapeutic intervention techniques', category: 'technical', importance: 'required' },
      { skill: 'Activity analysis and adaptation', category: 'technical', importance: 'required' },
      { skill: 'Documentation and reporting', category: 'technical', importance: 'required' },
      { skill: 'Medical terminology', category: 'technical', importance: 'required' },
      { skill: 'Empathy', category: 'soft', importance: 'required' },
      { skill: 'Patience', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Creativity', category: 'soft', importance: 'required' },
      { skill: 'CTRS (Certified Therapeutic Recreation Specialist)', category: 'certification', importance: 'required' },
      { skill: 'CPR/First Aid', category: 'certification', importance: 'required' },
      { skill: 'State licensure (where required)', category: 'certification', importance: 'required' },
    ],
    salaryRanges: [
      { min: 42000, max: 52000, median: 47000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 50000, max: 62000, median: 56000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 58000, max: 75000, median: 66500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Recreational Therapist',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 42000, max: 52000, median: 47000, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Client assessment', 'Treatment implementation', 'Documentation', 'Activity facilitation'],
        requiredSkills: ['CTRS certification', 'Assessment skills', 'Treatment planning'],
      },
      {
        level: 'mid',
        title: 'Senior Recreational Therapist',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 50000, max: 62000, median: 56000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Complex case management', 'Specialized interventions', 'Student supervision', 'Program development'],
        requiredSkills: ['Advanced clinical skills', 'Mentoring', 'Specialized training'],
      },
      {
        level: 'senior',
        title: 'Lead Recreational Therapist',
        yearsExperience: '5-10 years',
        typicalSalaryRange: { min: 58000, max: 75000, median: 66500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Team coordination', 'Quality assurance', 'Staff training', 'Program oversight'],
        requiredSkills: ['Leadership', 'Clinical expertise', 'Quality management'],
      },
      {
        level: 'executive',
        title: 'Director of Recreational Therapy',
        yearsExperience: '10+ years',
        typicalSalaryRange: { min: 65000, max: 90000, median: 77500, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Department management', 'Budget oversight', 'Strategic planning', 'Regulatory compliance'],
        requiredSkills: ['Executive leadership', 'Business management', 'Strategic planning'],
      },
    ],
    industryInsights: [
      {
        topic: 'Aging population',
        description: 'Growing demand in senior care facilities and memory care programs',
        trend: 'growing',
      },
      {
        topic: 'Mental health integration',
        description: 'Expanded role in mental health treatment and substance abuse recovery',
        trend: 'growing',
      },
      {
        topic: 'Community-based services',
        description: 'Shift toward community integration and inclusive recreation programs',
        trend: 'growing',
      },
      {
        topic: 'Evidence-based practice',
        description: 'Increased emphasis on research and outcome measurement',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: false,
      hybrid: false,
      onsite: true,
      travelRequired: false,
      typicalHours: '40 hours per week, some evenings/weekends depending on setting',
    },
    jobOutlook: {
      growthRate: '4% (2022-2032, about as fast as average)',
      projectedJobs: '1,900 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: "Bachelor's degree in recreational therapy or related field",
      preferredDegree: "Bachelor's degree from CTRS-accredited program",
      certifications: ['CTRS (Certified Therapeutic Recreation Specialist)', 'CPR/First Aid', 'State licensure (if required)'],
      alternativePathways: ['Master\\s degree in recreational therapy', 'Related degree with RT coursework', 'Clinical internship completion'],
    },
    relatedRoles: ['Activity Director', 'Occupational Therapist', 'Art Therapist', 'Music Therapist', 'Social Worker'],
    keywords: ['recreational therapy', 'therapeutic recreation', 'CTRS', 'activity therapy', 'rehabilitation', 'recreation therapist'],
  },
  {
    id: 'wellness-center-director',
    category: 'wellness',
    title: 'Wellness Center Director',
    description: 'Wellness Center Directors provide executive leadership for wellness facilities, overseeing all operations including strategic planning, financial management, staff leadership, program development, marketing, and ensuring the center meets business objectives while delivering exceptional member experiences.',
    alternativeTitles: ['Wellness Facility Director', 'Health and Wellness Director', 'Community Wellness Director', 'Fitness and Wellness Director'],
    dailyTasks: [
      { task: 'Oversee all facility operations and department management', frequency: 'daily', timePercentage: 20 },
      { task: 'Develop strategic plans and business objectives', frequency: 'weekly', timePercentage: 15 },
      { task: 'Manage P&L, budgets, and financial performance', frequency: 'daily', timePercentage: 15 },
      { task: 'Lead and develop management team', frequency: 'daily', timePercentage: 15 },
      { task: 'Build community partnerships and relationships', frequency: 'weekly', timePercentage: 10 },
      { task: 'Oversee marketing and membership growth initiatives', frequency: 'weekly', timePercentage: 10 },
      { task: 'Ensure regulatory compliance and risk management', frequency: 'daily', timePercentage: 10 },
      { task: 'Monitor facility maintenance and capital improvements', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Strategic planning', category: 'technical', importance: 'required', description: 'Ability to develop long-term organizational strategy' },
      { skill: 'Financial management', category: 'technical', importance: 'required' },
      { skill: 'Operations management', category: 'technical', importance: 'required' },
      { skill: 'Business development', category: 'technical', importance: 'required' },
      { skill: 'Program development', category: 'technical', importance: 'required' },
      { skill: 'Leadership', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Decision-making', category: 'soft', importance: 'required' },
      { skill: 'Change management', category: 'soft', importance: 'preferred' },
      { skill: 'ACSM certifications', category: 'certification', importance: 'preferred' },
      { skill: 'MBA or MHA', category: 'certification', importance: 'nice-to-have' },
      { skill: 'CPR/AED', category: 'certification', importance: 'required' },
    ],
    salaryRanges: [
      { min: 55000, max: 72000, median: 63500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 68000, max: 90000, median: 79000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 85000, max: 120000, median: 102500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Assistant Wellness Director',
        yearsExperience: '0-3 years',
        typicalSalaryRange: { min: 55000, max: 72000, median: 63500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Department oversight', 'Program management', 'Staff supervision', 'Operational support'],
        requiredSkills: ['Management experience', 'Program development', 'Team leadership'],
      },
      {
        level: 'mid',
        title: 'Wellness Center Director',
        yearsExperience: '3-7 years',
        typicalSalaryRange: { min: 68000, max: 90000, median: 79000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Full facility leadership', 'Financial management', 'Strategic planning', 'Community engagement'],
        requiredSkills: ['Executive leadership', 'Financial acumen', 'Strategic thinking'],
      },
      {
        level: 'senior',
        title: 'Senior Wellness Director',
        yearsExperience: '7-12 years',
        typicalSalaryRange: { min: 85000, max: 120000, median: 102500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Large facility leadership', 'Multi-site oversight', 'Business growth', 'Executive strategy'],
        requiredSkills: ['Advanced leadership', 'Business strategy', 'Change leadership'],
      },
      {
        level: 'executive',
        title: 'Vice President of Wellness / Regional Director',
        yearsExperience: '12+ years',
        typicalSalaryRange: { min: 100000, max: 150000, median: 125000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Multi-facility oversight', 'Enterprise strategy', 'Executive leadership', 'Organizational growth'],
        requiredSkills: ['Executive leadership', 'Strategic vision', 'Business development'],
      },
    ],
    industryInsights: [
      {
        topic: 'Medical fitness facilities',
        description: 'Growth in hospital-affiliated and medically-integrated wellness centers',
        trend: 'growing',
      },
      {
        topic: 'Value-based care',
        description: 'Healthcare partnerships creating new wellness center opportunities',
        trend: 'growing',
      },
      {
        topic: 'Multi-generational programming',
        description: 'Centers adapting to serve diverse age groups and abilities',
        trend: 'growing',
      },
      {
        topic: 'Technology adoption',
        description: 'Digital integration transforming member experience and operations',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: false,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '50+ hours per week, including some evenings and weekends',
    },
    jobOutlook: {
      growthRate: '8% (2022-2032, faster than average)',
      projectedJobs: '4,200 openings per year',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: "Bachelor's degree in exercise science, health promotion, or related field",
      preferredDegree: "Master's degree in health administration, business, or exercise science",
      certifications: ['ACSM certifications', 'CPR/AED', 'First Aid', 'MBA/MHA (preferred)'],
      alternativePathways: ['Business background with wellness experience', 'Healthcare administration transition', 'Recreation management background'],
    },
    relatedRoles: ['Fitness Director', 'Recreation Director', 'Community Center Director', 'Corporate Wellness Director'],
    keywords: ['wellness director', 'fitness director', 'wellness center', 'facility management', 'wellness operations', 'health club director'],
  },
  {
    id: 'fitness-marketing-specialist',
    category: 'wellness',
    title: 'Fitness Marketing Specialist',
    description: 'Fitness Marketing Specialists develop and execute comprehensive marketing strategies for fitness facilities, wellness brands, personal trainers, and health companies. They create compelling campaigns, manage digital presence, drive membership growth, and build brand awareness in the competitive wellness industry.',
    alternativeTitles: ['Wellness Marketing Manager', 'Fitness Brand Specialist', 'Health and Wellness Marketing Manager', 'Gym Marketing Coordinator'],
    dailyTasks: [
      { task: 'Develop and execute digital marketing campaigns', frequency: 'daily', timePercentage: 20 },
      { task: 'Create content for social media and marketing materials', frequency: 'daily', timePercentage: 20 },
      { task: 'Analyze marketing metrics and campaign performance', frequency: 'daily', timePercentage: 15 },
      { task: 'Manage website, SEO, and online presence', frequency: 'daily', timePercentage: 15 },
      { task: 'Coordinate email marketing and member communications', frequency: 'daily', timePercentage: 10 },
      { task: 'Plan promotional events and member engagement initiatives', frequency: 'weekly', timePercentage: 10 },
      { task: 'Collaborate with sales team on lead generation', frequency: 'weekly', timePercentage: 5 },
      { task: 'Manage marketing budget and vendor relationships', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Digital marketing', category: 'technical', importance: 'required', description: 'Expertise in digital marketing strategies and platforms' },
      { skill: 'Social media marketing', category: 'technical', importance: 'required' },
      { skill: 'Content creation', category: 'technical', importance: 'required' },
      { skill: 'Marketing analytics', category: 'technical', importance: 'required' },
      { skill: 'SEO/SEM', category: 'technical', importance: 'preferred' },
      { skill: 'Creativity', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Project management', category: 'soft', importance: 'required' },
      { skill: 'Attention to detail', category: 'soft', importance: 'preferred' },
      { skill: 'Google Analytics certification', category: 'certification', importance: 'preferred' },
      { skill: 'Facebook Blueprint certification', category: 'certification', importance: 'nice-to-have' },
      { skill: 'HubSpot certification', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 42000, max: 55000, median: 48500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 52000, max: 70000, median: 61000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 65000, max: 90000, median: 77500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Fitness Marketing Coordinator',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 42000, max: 55000, median: 48500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Social media management', 'Content creation', 'Event coordination', 'Marketing support'],
        requiredSkills: ['Social media', 'Basic marketing', 'Content creation'],
      },
      {
        level: 'mid',
        title: 'Fitness Marketing Specialist',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 52000, max: 70000, median: 61000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Campaign management', 'Strategy development', 'Analytics and reporting', 'Digital advertising'],
        requiredSkills: ['Digital marketing', 'Campaign management', 'Analytics'],
      },
      {
        level: 'senior',
        title: 'Senior Marketing Manager',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 65000, max: 90000, median: 77500, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Marketing strategy', 'Team leadership', 'Brand development', 'Budget management'],
        requiredSkills: ['Strategic marketing', 'Leadership', 'Brand management'],
      },
      {
        level: 'executive',
        title: 'Director of Marketing',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 80000, max: 120000, median: 100000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Marketing department leadership', 'Strategic planning', 'Brand positioning', 'Growth strategy'],
        requiredSkills: ['Executive leadership', 'Strategic vision', 'Business development'],
      },
    ],
    industryInsights: [
      {
        topic: 'Influencer marketing',
        description: 'Growing use of fitness influencers and micro-influencers for brand promotion',
        trend: 'growing',
      },
      {
        topic: 'Video content dominance',
        description: 'Short-form video (TikTok, Reels, YouTube Shorts) becoming primary content format',
        trend: 'growing',
      },
      {
        topic: 'Personalized marketing',
        description: 'Data-driven personalization and targeted messaging increasing engagement',
        trend: 'growing',
      },
      {
        topic: 'Community building',
        description: 'Focus on building authentic communities versus transactional marketing',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: true,
      hybrid: true,
      onsite: true,
      travelRequired: false,
      typicalHours: '40-45 hours per week, flexible with occasional evening/weekend events',
    },
    jobOutlook: {
      growthRate: '10% (2022-2032, faster than average)',
      projectedJobs: '34,000 openings per year (marketing specialists overall)',
      competitionLevel: 'medium',
    },
    education: {
      minimumDegree: "Bachelor's degree in marketing, communications, or related field",
      preferredDegree: "Bachelor's in marketing, digital marketing, or business with marketing focus",
      certifications: ['Google Analytics', 'Google Ads', 'Facebook Blueprint', 'HubSpot', 'Hootsuite'],
      alternativePathways: ['Exercise science degree with marketing experience', 'Self-taught digital marketing', 'Marketing bootcamps'],
    },
    relatedRoles: ['Digital Marketing Manager', 'Social Media Manager', 'Brand Manager', 'Content Marketing Specialist'],
    keywords: ['fitness marketing', 'wellness marketing', 'gym marketing', 'digital marketing', 'social media marketing', 'health marketing'],
  },
  {
    id: 'sports-performance-analyst',
    category: 'wellness',
    title: 'Sports Performance Analyst',
    description: 'Sports Performance Analysts use data analytics, biomechanics, technology, and sports science to evaluate athlete performance, identify areas for improvement, reduce injury risk, and provide evidence-based recommendations to optimize training and competitive outcomes.',
    alternativeTitles: ['Performance Analyst', 'Sports Scientist', 'Athletic Performance Analyst', 'Sports Data Analyst'],
    dailyTasks: [
      { task: 'Collect and analyze performance data from training and competition', frequency: 'daily', timePercentage: 25 },
      { task: 'Create performance reports and visualizations for coaches', frequency: 'daily', timePercentage: 20 },
      { task: 'Monitor athlete workload and recovery metrics', frequency: 'daily', timePercentage: 15 },
      { task: 'Conduct video analysis and biomechanical assessments', frequency: 'daily', timePercentage: 15 },
      { task: 'Collaborate with coaching and sports medicine staff', frequency: 'daily', timePercentage: 10 },
      { task: 'Operate and maintain performance technology systems', frequency: 'daily', timePercentage: 5 },
      { task: 'Research and implement new analysis methods', frequency: 'weekly', timePercentage: 5 },
      { task: 'Present findings to coaches and performance team', frequency: 'weekly', timePercentage: 5 },
    ],
    requiredSkills: [
      { skill: 'Data analysis and statistics', category: 'technical', importance: 'required', description: 'Ability to analyze complex performance data' },
      { skill: 'Sports science knowledge', category: 'technical', importance: 'required' },
      { skill: 'Performance technology platforms', category: 'technical', importance: 'required' },
      { skill: 'Video analysis software', category: 'technical', importance: 'required' },
      { skill: 'Excel and data visualization', category: 'technical', importance: 'required' },
      { skill: 'Python or R programming', category: 'technical', importance: 'preferred' },
      { skill: 'Attention to detail', category: 'soft', importance: 'required' },
      { skill: 'Communication', category: 'soft', importance: 'required' },
      { skill: 'Problem-solving', category: 'soft', importance: 'required' },
      { skill: 'CSCS (Certified Strength and Conditioning Specialist)', category: 'certification', importance: 'preferred' },
      { skill: 'ACSM-EP', category: 'certification', importance: 'preferred' },
      { skill: 'Performance analysis certifications', category: 'certification', importance: 'nice-to-have' },
    ],
    salaryRanges: [
      { min: 40000, max: 55000, median: 47500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
      { min: 50000, max: 70000, median: 60000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
      { min: 65000, max: 95000, median: 80000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
    ],
    careerProgression: [
      {
        level: 'entry',
        title: 'Performance Analyst',
        yearsExperience: '0-2 years',
        typicalSalaryRange: { min: 40000, max: 55000, median: 47500, currency: 'USD', period: 'yearly', experienceLevel: 'entry' },
        keyResponsibilities: ['Data collection', 'Basic analysis', 'Report generation', 'Technology support'],
        requiredSkills: ['Data analysis', 'Sports science basics', 'Technology proficiency'],
      },
      {
        level: 'mid',
        title: 'Sports Performance Analyst',
        yearsExperience: '2-5 years',
        typicalSalaryRange: { min: 50000, max: 70000, median: 60000, currency: 'USD', period: 'yearly', experienceLevel: 'mid' },
        keyResponsibilities: ['Advanced analysis', 'Performance optimization', 'Strategic insights', 'Coach collaboration'],
        requiredSkills: ['Advanced analytics', 'Programming', 'Sports performance expertise'],
      },
      {
        level: 'senior',
        title: 'Lead Performance Analyst',
        yearsExperience: '5-8 years',
        typicalSalaryRange: { min: 65000, max: 95000, median: 80000, currency: 'USD', period: 'yearly', experienceLevel: 'senior' },
        keyResponsibilities: ['Team leadership', 'System development', 'Strategic planning', 'Cross-functional leadership'],
        requiredSkills: ['Leadership', 'Advanced analytics', 'Strategic thinking'],
      },
      {
        level: 'executive',
        title: 'Director of Performance Analysis',
        yearsExperience: '8+ years',
        typicalSalaryRange: { min: 80000, max: 130000, median: 105000, currency: 'USD', period: 'yearly', experienceLevel: 'executive' },
        keyResponsibilities: ['Department leadership', 'Technology strategy', 'Performance systems', 'Organizational impact'],
        requiredSkills: ['Executive leadership', 'Technology strategy', 'Performance science'],
      },
    ],
    industryInsights: [
      {
        topic: 'Wearable technology growth',
        description: 'Advanced wearables and GPS tracking becoming standard in performance analysis',
        trend: 'growing',
      },
      {
        topic: 'AI and machine learning',
        description: 'AI-powered analysis tools transforming performance insights',
        trend: 'growing',
      },
      {
        topic: 'Injury prevention focus',
        description: 'Growing emphasis on using data to predict and prevent injuries',
        trend: 'growing',
      },
      {
        topic: 'Collegiate expansion',
        description: 'More college programs investing in performance analysis positions',
        trend: 'growing',
      },
    ],
    workEnvironment: {
      remote: false,
      hybrid: true,
      onsite: true,
      travelRequired: true,
      typicalHours: '45-50 hours per week, including evenings/weekends during season',
    },
    jobOutlook: {
      growthRate: '23% (2022-2032, much faster than average - data analyst roles)',
      projectedJobs: '17,700 openings per year (sports-related subset)',
      competitionLevel: 'high',
    },
    education: {
      minimumDegree: "Bachelor's degree in exercise science, kinesiology, or sports science",
      preferredDegree: "Bachelor's or Master's in sports science, data analytics, or biomechanics",
      certifications: ['CSCS', 'ACSM-EP', 'Performance analysis certifications', 'Statistics/data science courses'],
      alternativePathways: ['Data science degree with sports focus', 'Computer science with sports analytics', 'Athletic training background with analytics training'],
    },
    relatedRoles: ['Sports Scientist', 'Biomechanist', 'Strength and Conditioning Coach', 'Athletic Trainer', 'Data Analyst'],
    keywords: ['sports performance', 'performance analyst', 'sports analytics', 'sports science', 'athletic performance', 'sports data'],
  },
];